// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backfillAccountOpeningDate = `-- name: BackfillAccountOpeningDate :exec
UPDATE accounts
SET opening_balance_date = $1::date
WHERE workspace_id = $2
  AND id = $3
  AND opening_balance_date > $1::date
`

type BackfillAccountOpeningDateParams struct {
	NewDate     time.Time `json:"new_date"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
}

// Move the opening-balance anchor back when a later import lands rows that
// pre-date the existing one (e.g. a savings-statement import covering a
// period before the account's first consolidated-MMF interest event).
// Without this, the balance query's `booked_at >= opening_balance_date`
// filter silently excludes the early rows from the displayed balance even
// though they were inserted. Only shifts when @new_date is strictly
// earlier — a no-op if already covered.
func (q *Queries) BackfillAccountOpeningDate(ctx context.Context, arg BackfillAccountOpeningDateParams) error {
	_, err := q.db.Exec(ctx, backfillAccountOpeningDate, arg.NewDate, arg.WorkspaceID, arg.AccountID)
	return err
}

const backfillOpeningSnapshot = `-- name: BackfillOpeningSnapshot :exec
UPDATE account_balance_snapshots
SET as_of = $1::timestamptz
WHERE workspace_id = $2
  AND account_id = $3
  AND source = 'opening'
  AND as_of > $1::timestamptz
`

type BackfillOpeningSnapshotParams struct {
	NewAsOf     time.Time `json:"new_as_of"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
}

// Companion to BackfillAccountOpeningDate. The balance query reads from
// the latest snapshot's as_of when present, so updating only the account
// column is insufficient — the snapshot has to move with it.
func (q *Queries) BackfillOpeningSnapshot(ctx context.Context, arg BackfillOpeningSnapshotParams) error {
	_, err := q.db.Exec(ctx, backfillOpeningSnapshot, arg.NewAsOf, arg.WorkspaceID, arg.AccountID)
	return err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE workspace_id = $1 AND id = $2
`

type DeleteAccountParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAccountSourceRefs = `-- name: DeleteAccountSourceRefs :exec
DELETE FROM source_refs sr
WHERE sr.workspace_id = $1
  AND sr.entity_type = 'transaction'
  AND sr.entity_id IN (
    SELECT tx.id FROM transactions tx WHERE tx.workspace_id = $1 AND tx.account_id = $2
  )
`

type DeleteAccountSourceRefsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
}

func (q *Queries) DeleteAccountSourceRefs(ctx context.Context, arg DeleteAccountSourceRefsParams) error {
	_, err := q.db.Exec(ctx, deleteAccountSourceRefs, arg.WorkspaceID, arg.AccountID)
	return err
}

const getAccountWithBalance = `-- name: GetAccountWithBalance :one

SELECT
  a.id, a.workspace_id, a.name, a.nickname, a.kind::text AS kind, a.currency, a.institution,
  a.account_group_id, a.account_sort_order,
  a.open_date, a.close_date, a.opening_balance::text AS opening_balance, a.opening_balance_date,
  a.include_in_networth, a.include_in_savings_rate, a.archived_at,
  a.created_at, a.updated_at,
  CASE
    WHEN t.max_booked_at IS NULL THEN s.as_of
    WHEN s.as_of IS NULL THEN t.max_booked_at::timestamp AT TIME ZONE 'UTC'
    WHEN t.max_booked_at::timestamp AT TIME ZONE 'UTC' > s.as_of THEN t.max_booked_at::timestamp AT TIME ZONE 'UTC'
    ELSE s.as_of
  END AS balance_as_of,
  (coalesce(s.balance, a.opening_balance) + coalesce(t.post_sum, 0))::text AS balance
FROM accounts a
LEFT JOIN LATERAL (
  SELECT balance, as_of
  FROM account_balance_snapshots
  WHERE account_id = a.id
  ORDER BY as_of DESC
  LIMIT 1
) s ON true
LEFT JOIN LATERAL (
  SELECT coalesce(sum(amount), 0) AS post_sum, max(booked_at) AS max_booked_at
  FROM transactions
  WHERE account_id = a.id
    AND status IN ('posted', 'reconciled')
    AND booked_at >= (coalesce(s.as_of, a.opening_balance_date::timestamptz)
                        AT TIME ZONE 'UTC')::date
) t ON true
WHERE a.workspace_id = $1 AND a.id = $2
`

type GetAccountWithBalanceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

type GetAccountWithBalanceRow struct {
	ID                   uuid.UUID   `json:"id"`
	WorkspaceID          uuid.UUID   `json:"workspace_id"`
	Name                 string      `json:"name"`
	Nickname             *string     `json:"nickname"`
	Kind                 string      `json:"kind"`
	Currency             string      `json:"currency"`
	Institution          *string     `json:"institution"`
	AccountGroupID       *uuid.UUID  `json:"account_group_id"`
	AccountSortOrder     int32       `json:"account_sort_order"`
	OpenDate             time.Time   `json:"open_date"`
	CloseDate            *time.Time  `json:"close_date"`
	OpeningBalance       string      `json:"opening_balance"`
	OpeningBalanceDate   time.Time   `json:"opening_balance_date"`
	IncludeInNetworth    bool        `json:"include_in_networth"`
	IncludeInSavingsRate bool        `json:"include_in_savings_rate"`
	ArchivedAt           *time.Time  `json:"archived_at"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	BalanceAsOf          interface{} `json:"balance_as_of"`
	Balance              string      `json:"balance"`
}

// Derived balance rule (spec §5.2):
//
//	balance = coalesce(latest_snapshot.balance, opening_balance)
//	        + sum(transactions.amount where status in ('posted','reconciled')
//	              and booked_at >= snapshot.as_of projected to UTC date)
//
// Every account has an "opening" snapshot at create time, so post-opening-day
// transactions are included correctly.
func (q *Queries) GetAccountWithBalance(ctx context.Context, arg GetAccountWithBalanceParams) (GetAccountWithBalanceRow, error) {
	row := q.db.QueryRow(ctx, getAccountWithBalance, arg.WorkspaceID, arg.ID)
	var i GetAccountWithBalanceRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Nickname,
		&i.Kind,
		&i.Currency,
		&i.Institution,
		&i.AccountGroupID,
		&i.AccountSortOrder,
		&i.OpenDate,
		&i.CloseDate,
		&i.OpeningBalance,
		&i.OpeningBalanceDate,
		&i.IncludeInNetworth,
		&i.IncludeInSavingsRate,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BalanceAsOf,
		&i.Balance,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (
  id, workspace_id, name, nickname, kind, currency, institution,
  account_group_id, account_sort_order,
  open_date, opening_balance, opening_balance_date,
  include_in_networth, include_in_savings_rate
) VALUES (
  $1, $2, $3, $4, $5::account_kind, $6, $7,
  $8,
  coalesce((
    SELECT max(account_sort_order) + 1000
    FROM accounts
    WHERE workspace_id = $2
      AND account_group_id IS NOT DISTINCT FROM $8::uuid
  ), 1000),
  $9, $10::numeric, $11,
  $12, $13
)
RETURNING id, workspace_id, name, nickname, kind::text AS kind, currency, institution,
          account_group_id, account_sort_order,
          open_date, close_date, opening_balance::text AS opening_balance, opening_balance_date,
          include_in_networth, include_in_savings_rate, archived_at,
          created_at, updated_at
`

type InsertAccountParams struct {
	ID                   uuid.UUID      `json:"id"`
	WorkspaceID          uuid.UUID      `json:"workspace_id"`
	Name                 string         `json:"name"`
	Nickname             *string        `json:"nickname"`
	Kind                 AccountKind    `json:"kind"`
	Currency             string         `json:"currency"`
	Institution          *string        `json:"institution"`
	AccountGroupID       *uuid.UUID     `json:"account_group_id"`
	OpenDate             time.Time      `json:"open_date"`
	OpeningBalance       pgtype.Numeric `json:"opening_balance"`
	OpeningBalanceDate   time.Time      `json:"opening_balance_date"`
	IncludeInNetworth    bool           `json:"include_in_networth"`
	IncludeInSavingsRate bool           `json:"include_in_savings_rate"`
}

type InsertAccountRow struct {
	ID                   uuid.UUID  `json:"id"`
	WorkspaceID          uuid.UUID  `json:"workspace_id"`
	Name                 string     `json:"name"`
	Nickname             *string    `json:"nickname"`
	Kind                 string     `json:"kind"`
	Currency             string     `json:"currency"`
	Institution          *string    `json:"institution"`
	AccountGroupID       *uuid.UUID `json:"account_group_id"`
	AccountSortOrder     int32      `json:"account_sort_order"`
	OpenDate             time.Time  `json:"open_date"`
	CloseDate            *time.Time `json:"close_date"`
	OpeningBalance       string     `json:"opening_balance"`
	OpeningBalanceDate   time.Time  `json:"opening_balance_date"`
	IncludeInNetworth    bool       `json:"include_in_networth"`
	IncludeInSavingsRate bool       `json:"include_in_savings_rate"`
	ArchivedAt           *time.Time `json:"archived_at"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (InsertAccountRow, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Nickname,
		arg.Kind,
		arg.Currency,
		arg.Institution,
		arg.AccountGroupID,
		arg.OpenDate,
		arg.OpeningBalance,
		arg.OpeningBalanceDate,
		arg.IncludeInNetworth,
		arg.IncludeInSavingsRate,
	)
	var i InsertAccountRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Nickname,
		&i.Kind,
		&i.Currency,
		&i.Institution,
		&i.AccountGroupID,
		&i.AccountSortOrder,
		&i.OpenDate,
		&i.CloseDate,
		&i.OpeningBalance,
		&i.OpeningBalanceDate,
		&i.IncludeInNetworth,
		&i.IncludeInSavingsRate,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOpeningSnapshot = `-- name: InsertOpeningSnapshot :exec
INSERT INTO account_balance_snapshots (
  id, workspace_id, account_id, as_of, balance, currency, source
) VALUES (
  $1, $2, $3, $4, $5::numeric, $6, 'opening'
)
`

type InsertOpeningSnapshotParams struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	AccountID   uuid.UUID      `json:"account_id"`
	AsOf        time.Time      `json:"as_of"`
	Balance     pgtype.Numeric `json:"balance"`
	Currency    string         `json:"currency"`
}

func (q *Queries) InsertOpeningSnapshot(ctx context.Context, arg InsertOpeningSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertOpeningSnapshot,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.AsOf,
		arg.Balance,
		arg.Currency,
	)
	return err
}

const listAccountsWithBalance = `-- name: ListAccountsWithBalance :many
SELECT
  a.id, a.workspace_id, a.name, a.nickname, a.kind::text AS kind, a.currency, a.institution,
  a.account_group_id, a.account_sort_order,
  a.open_date, a.close_date, a.opening_balance::text AS opening_balance, a.opening_balance_date,
  a.include_in_networth, a.include_in_savings_rate, a.archived_at,
  a.created_at, a.updated_at,
  CASE
    WHEN t.max_booked_at IS NULL THEN s.as_of
    WHEN s.as_of IS NULL THEN t.max_booked_at::timestamp AT TIME ZONE 'UTC'
    WHEN t.max_booked_at::timestamp AT TIME ZONE 'UTC' > s.as_of THEN t.max_booked_at::timestamp AT TIME ZONE 'UTC'
    ELSE s.as_of
  END AS balance_as_of,
  (coalesce(s.balance, a.opening_balance) + coalesce(t.post_sum, 0))::text AS balance
FROM accounts a
LEFT JOIN LATERAL (
  SELECT balance, as_of
  FROM account_balance_snapshots
  WHERE account_id = a.id
  ORDER BY as_of DESC
  LIMIT 1
) s ON true
LEFT JOIN LATERAL (
  SELECT coalesce(sum(amount), 0) AS post_sum, max(booked_at) AS max_booked_at
  FROM transactions
  WHERE account_id = a.id
    AND status IN ('posted', 'reconciled')
    AND booked_at >= (coalesce(s.as_of, a.opening_balance_date::timestamptz)
                        AT TIME ZONE 'UTC')::date
) t ON true
WHERE a.workspace_id = $1
ORDER BY a.account_group_id NULLS FIRST, a.account_sort_order, a.created_at
`

type ListAccountsWithBalanceRow struct {
	ID                   uuid.UUID   `json:"id"`
	WorkspaceID          uuid.UUID   `json:"workspace_id"`
	Name                 string      `json:"name"`
	Nickname             *string     `json:"nickname"`
	Kind                 string      `json:"kind"`
	Currency             string      `json:"currency"`
	Institution          *string     `json:"institution"`
	AccountGroupID       *uuid.UUID  `json:"account_group_id"`
	AccountSortOrder     int32       `json:"account_sort_order"`
	OpenDate             time.Time   `json:"open_date"`
	CloseDate            *time.Time  `json:"close_date"`
	OpeningBalance       string      `json:"opening_balance"`
	OpeningBalanceDate   time.Time   `json:"opening_balance_date"`
	IncludeInNetworth    bool        `json:"include_in_networth"`
	IncludeInSavingsRate bool        `json:"include_in_savings_rate"`
	ArchivedAt           *time.Time  `json:"archived_at"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	BalanceAsOf          interface{} `json:"balance_as_of"`
	Balance              string      `json:"balance"`
}

func (q *Queries) ListAccountsWithBalance(ctx context.Context, workspaceID uuid.UUID) ([]ListAccountsWithBalanceRow, error) {
	rows, err := q.db.Query(ctx, listAccountsWithBalance, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsWithBalanceRow{}
	for rows.Next() {
		var i ListAccountsWithBalanceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Nickname,
			&i.Kind,
			&i.Currency,
			&i.Institution,
			&i.AccountGroupID,
			&i.AccountSortOrder,
			&i.OpenDate,
			&i.CloseDate,
			&i.OpeningBalance,
			&i.OpeningBalanceDate,
			&i.IncludeInNetworth,
			&i.IncludeInSavingsRate,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BalanceAsOf,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsWithBalanceActive = `-- name: ListAccountsWithBalanceActive :many
SELECT
  a.id, a.workspace_id, a.name, a.nickname, a.kind::text AS kind, a.currency, a.institution,
  a.account_group_id, a.account_sort_order,
  a.open_date, a.close_date, a.opening_balance::text AS opening_balance, a.opening_balance_date,
  a.include_in_networth, a.include_in_savings_rate, a.archived_at,
  a.created_at, a.updated_at,
  CASE
    WHEN t.max_booked_at IS NULL THEN s.as_of
    WHEN s.as_of IS NULL THEN t.max_booked_at::timestamp AT TIME ZONE 'UTC'
    WHEN t.max_booked_at::timestamp AT TIME ZONE 'UTC' > s.as_of THEN t.max_booked_at::timestamp AT TIME ZONE 'UTC'
    ELSE s.as_of
  END AS balance_as_of,
  (coalesce(s.balance, a.opening_balance) + coalesce(t.post_sum, 0))::text AS balance
FROM accounts a
LEFT JOIN LATERAL (
  SELECT balance, as_of
  FROM account_balance_snapshots
  WHERE account_id = a.id
  ORDER BY as_of DESC
  LIMIT 1
) s ON true
LEFT JOIN LATERAL (
  SELECT coalesce(sum(amount), 0) AS post_sum, max(booked_at) AS max_booked_at
  FROM transactions
  WHERE account_id = a.id
    AND status IN ('posted', 'reconciled')
    AND booked_at >= (coalesce(s.as_of, a.opening_balance_date::timestamptz)
                        AT TIME ZONE 'UTC')::date
) t ON true
WHERE a.workspace_id = $1 AND a.archived_at IS NULL
ORDER BY a.account_group_id NULLS FIRST, a.account_sort_order, a.created_at
`

type ListAccountsWithBalanceActiveRow struct {
	ID                   uuid.UUID   `json:"id"`
	WorkspaceID          uuid.UUID   `json:"workspace_id"`
	Name                 string      `json:"name"`
	Nickname             *string     `json:"nickname"`
	Kind                 string      `json:"kind"`
	Currency             string      `json:"currency"`
	Institution          *string     `json:"institution"`
	AccountGroupID       *uuid.UUID  `json:"account_group_id"`
	AccountSortOrder     int32       `json:"account_sort_order"`
	OpenDate             time.Time   `json:"open_date"`
	CloseDate            *time.Time  `json:"close_date"`
	OpeningBalance       string      `json:"opening_balance"`
	OpeningBalanceDate   time.Time   `json:"opening_balance_date"`
	IncludeInNetworth    bool        `json:"include_in_networth"`
	IncludeInSavingsRate bool        `json:"include_in_savings_rate"`
	ArchivedAt           *time.Time  `json:"archived_at"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	BalanceAsOf          interface{} `json:"balance_as_of"`
	Balance              string      `json:"balance"`
}

func (q *Queries) ListAccountsWithBalanceActive(ctx context.Context, workspaceID uuid.UUID) ([]ListAccountsWithBalanceActiveRow, error) {
	rows, err := q.db.Query(ctx, listAccountsWithBalanceActive, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsWithBalanceActiveRow{}
	for rows.Next() {
		var i ListAccountsWithBalanceActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Nickname,
			&i.Kind,
			&i.Currency,
			&i.Institution,
			&i.AccountGroupID,
			&i.AccountSortOrder,
			&i.OpenDate,
			&i.CloseDate,
			&i.OpeningBalance,
			&i.OpeningBalanceDate,
			&i.IncludeInNetworth,
			&i.IncludeInSavingsRate,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BalanceAsOf,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
