// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_groups.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearAccountGroupMembership = `-- name: ClearAccountGroupMembership :exec
UPDATE accounts
SET account_group_id = NULL
WHERE workspace_id = $1 AND account_group_id = $2::uuid
`

type ClearAccountGroupMembershipParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	GroupID     uuid.UUID `json:"group_id"`
}

func (q *Queries) ClearAccountGroupMembership(ctx context.Context, arg ClearAccountGroupMembershipParams) error {
	_, err := q.db.Exec(ctx, clearAccountGroupMembership, arg.WorkspaceID, arg.GroupID)
	return err
}

const deleteAccountGroup = `-- name: DeleteAccountGroup :execrows
DELETE FROM account_groups WHERE workspace_id = $1 AND id = $2
`

type DeleteAccountGroupParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) DeleteAccountGroup(ctx context.Context, arg DeleteAccountGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountGroup, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountGroup = `-- name: GetAccountGroup :one
SELECT id, workspace_id, name, sort_order, aggregate_balances, archived_at, created_at, updated_at
FROM account_groups
WHERE workspace_id = $1 AND id = $2
`

type GetAccountGroupParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

type GetAccountGroupRow struct {
	ID                uuid.UUID  `json:"id"`
	WorkspaceID       uuid.UUID  `json:"workspace_id"`
	Name              string     `json:"name"`
	SortOrder         int32      `json:"sort_order"`
	AggregateBalances bool       `json:"aggregate_balances"`
	ArchivedAt        *time.Time `json:"archived_at"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

func (q *Queries) GetAccountGroup(ctx context.Context, arg GetAccountGroupParams) (GetAccountGroupRow, error) {
	row := q.db.QueryRow(ctx, getAccountGroup, arg.WorkspaceID, arg.ID)
	var i GetAccountGroupRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.SortOrder,
		&i.AggregateBalances,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAccountGroup = `-- name: InsertAccountGroup :one
INSERT INTO account_groups (id, workspace_id, name, aggregate_balances, sort_order)
VALUES (
  $1, $2, $3, $4,
  coalesce((SELECT max(sort_order) + 1000 FROM account_groups WHERE workspace_id = $2), 1000)
)
RETURNING id, workspace_id, name, sort_order, aggregate_balances, archived_at, created_at, updated_at
`

type InsertAccountGroupParams struct {
	ID                uuid.UUID `json:"id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
	Name              string    `json:"name"`
	AggregateBalances bool      `json:"aggregate_balances"`
}

type InsertAccountGroupRow struct {
	ID                uuid.UUID  `json:"id"`
	WorkspaceID       uuid.UUID  `json:"workspace_id"`
	Name              string     `json:"name"`
	SortOrder         int32      `json:"sort_order"`
	AggregateBalances bool       `json:"aggregate_balances"`
	ArchivedAt        *time.Time `json:"archived_at"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

func (q *Queries) InsertAccountGroup(ctx context.Context, arg InsertAccountGroupParams) (InsertAccountGroupRow, error) {
	row := q.db.QueryRow(ctx, insertAccountGroup,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.AggregateBalances,
	)
	var i InsertAccountGroupRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.SortOrder,
		&i.AggregateBalances,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountGroups = `-- name: ListAccountGroups :many
SELECT id, workspace_id, name, sort_order, aggregate_balances, archived_at, created_at, updated_at
FROM account_groups
WHERE workspace_id = $1
ORDER BY sort_order, created_at
`

type ListAccountGroupsRow struct {
	ID                uuid.UUID  `json:"id"`
	WorkspaceID       uuid.UUID  `json:"workspace_id"`
	Name              string     `json:"name"`
	SortOrder         int32      `json:"sort_order"`
	AggregateBalances bool       `json:"aggregate_balances"`
	ArchivedAt        *time.Time `json:"archived_at"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

func (q *Queries) ListAccountGroups(ctx context.Context, workspaceID uuid.UUID) ([]ListAccountGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAccountGroups, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountGroupsRow{}
	for rows.Next() {
		var i ListAccountGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.SortOrder,
			&i.AggregateBalances,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountGroupsActive = `-- name: ListAccountGroupsActive :many
SELECT id, workspace_id, name, sort_order, aggregate_balances, archived_at, created_at, updated_at
FROM account_groups
WHERE workspace_id = $1 AND archived_at IS NULL
ORDER BY sort_order, created_at
`

type ListAccountGroupsActiveRow struct {
	ID                uuid.UUID  `json:"id"`
	WorkspaceID       uuid.UUID  `json:"workspace_id"`
	Name              string     `json:"name"`
	SortOrder         int32      `json:"sort_order"`
	AggregateBalances bool       `json:"aggregate_balances"`
	ArchivedAt        *time.Time `json:"archived_at"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

func (q *Queries) ListAccountGroupsActive(ctx context.Context, workspaceID uuid.UUID) ([]ListAccountGroupsActiveRow, error) {
	rows, err := q.db.Query(ctx, listAccountGroupsActive, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountGroupsActiveRow{}
	for rows.Next() {
		var i ListAccountGroupsActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.SortOrder,
			&i.AggregateBalances,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderAccount = `-- name: ReorderAccount :execrows
UPDATE accounts
SET account_group_id = $1, account_sort_order = $2
WHERE workspace_id = $3 AND id = $4
`

type ReorderAccountParams struct {
	AccountGroupID   *uuid.UUID `json:"account_group_id"`
	AccountSortOrder int32      `json:"account_sort_order"`
	WorkspaceID      uuid.UUID  `json:"workspace_id"`
	ID               uuid.UUID  `json:"id"`
}

func (q *Queries) ReorderAccount(ctx context.Context, arg ReorderAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderAccount,
		arg.AccountGroupID,
		arg.AccountSortOrder,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderAccountGroup = `-- name: ReorderAccountGroup :execrows
UPDATE account_groups
SET sort_order = $1
WHERE workspace_id = $2 AND id = $3
`

type ReorderAccountGroupParams struct {
	SortOrder   int32     `json:"sort_order"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) ReorderAccountGroup(ctx context.Context, arg ReorderAccountGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderAccountGroup, arg.SortOrder, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
