// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_grants.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const adminCountAdmins = `-- name: AdminCountAdmins :one
SELECT count(*) FROM users WHERE is_admin = true
`

func (q *Queries) AdminCountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetUserIsAdminForUpdate = `-- name: AdminGetUserIsAdminForUpdate :one
SELECT is_admin FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) AdminGetUserIsAdminForUpdate(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, adminGetUserIsAdminForUpdate, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const adminSetUserAdmin = `-- name: AdminSetUserAdmin :exec
UPDATE users SET is_admin = $1, updated_at = now() WHERE id = $2
`

type AdminSetUserAdminParams struct {
	IsAdmin bool      `json:"is_admin"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) AdminSetUserAdmin(ctx context.Context, arg AdminSetUserAdminParams) error {
	_, err := q.db.Exec(ctx, adminSetUserAdmin, arg.IsAdmin, arg.ID)
	return err
}
