// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_users.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminCountUnusedRecoveryCodes = `-- name: AdminCountUnusedRecoveryCodes :one
SELECT count(*) FROM auth_recovery_codes WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) AdminCountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetUserDetail = `-- name: AdminGetUserDetail :one
SELECT id, email::text, display_name, email_verified_at, is_admin, last_workspace_id, created_at, last_login_at
FROM users WHERE id = $1
`

type AdminGetUserDetailRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	IsAdmin         bool       `json:"is_admin"`
	LastWorkspaceID *uuid.UUID `json:"last_workspace_id"`
	CreatedAt       time.Time  `json:"created_at"`
	LastLoginAt     *time.Time `json:"last_login_at"`
}

func (q *Queries) AdminGetUserDetail(ctx context.Context, id uuid.UUID) (AdminGetUserDetailRow, error) {
	row := q.db.QueryRow(ctx, adminGetUserDetail, id)
	var i AdminGetUserDetailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.LastWorkspaceID,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const adminListUserActiveSessions = `-- name: AdminListUserActiveSessions :many
SELECT id, created_at, last_seen_at, coalesce(user_agent, '') AS user_agent, coalesce(host(ip), '')::text AS ip
FROM sessions
WHERE user_id = $1 AND expires_at > now()
ORDER BY last_seen_at DESC
`

type AdminListUserActiveSessionsRow struct {
	ID         string    `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
	UserAgent  string    `json:"user_agent"`
	Ip         string    `json:"ip"`
}

func (q *Queries) AdminListUserActiveSessions(ctx context.Context, userID uuid.UUID) ([]AdminListUserActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, adminListUserActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserActiveSessionsRow{}
	for rows.Next() {
		var i AdminListUserActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.UserAgent,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUserMemberships = `-- name: AdminListUserMemberships :many
SELECT t.id AS workspace_id, t.name AS workspace_name, t.slug::text AS workspace_slug, tm.role::text AS role, tm.created_at AS joined_at
FROM workspace_memberships tm JOIN workspaces t ON t.id = tm.workspace_id
WHERE tm.user_id = $1
ORDER BY tm.created_at DESC
`

type AdminListUserMembershipsRow struct {
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	WorkspaceName string    `json:"workspace_name"`
	WorkspaceSlug string    `json:"workspace_slug"`
	Role          string    `json:"role"`
	JoinedAt      time.Time `json:"joined_at"`
}

func (q *Queries) AdminListUserMemberships(ctx context.Context, userID uuid.UUID) ([]AdminListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, adminListUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserMembershipsRow{}
	for rows.Next() {
		var i AdminListUserMembershipsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUserPasskeys = `-- name: AdminListUserPasskeys :many
SELECT id, coalesce(label, '') AS label, created_at
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at DESC
`

type AdminListUserPasskeysRow struct {
	ID        uuid.UUID `json:"id"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AdminListUserPasskeys(ctx context.Context, userID uuid.UUID) ([]AdminListUserPasskeysRow, error) {
	rows, err := q.db.Query(ctx, adminListUserPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserPasskeysRow{}
	for rows.Next() {
		var i AdminListUserPasskeysRow
		if err := rows.Scan(&i.ID, &i.Label, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, email::text, display_name, email_verified_at, is_admin, last_workspace_id, created_at
FROM users
WHERE ($1::text = '' OR email::text ILIKE $2 OR display_name ILIKE $2 OR id::text ILIKE $2)
  AND (NOT $3::bool OR is_admin = true)
  AND ($4::timestamptz IS NULL OR (created_at, id) < ($4, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type AdminListUsersParams struct {
	Search          string     `json:"search"`
	SearchPattern   string     `json:"search_pattern"`
	IsAdminOnly     bool       `json:"is_admin_only"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	QueryLimit      int32      `json:"query_limit"`
}

type AdminListUsersRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	IsAdmin         bool       `json:"is_admin"`
	LastWorkspaceID *uuid.UUID `json:"last_workspace_id"`
	CreatedAt       time.Time  `json:"created_at"`
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Search,
		arg.SearchPattern,
		arg.IsAdminOnly,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.EmailVerifiedAt,
			&i.IsAdmin,
			&i.LastWorkspaceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUserHasTOTP = `-- name: AdminUserHasTOTP :one
SELECT exists(SELECT 1 FROM totp_credentials WHERE user_id = $1 AND verified_at IS NOT NULL) AS has_totp
`

func (q *Queries) AdminUserHasTOTP(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, adminUserHasTOTP, userID)
	var has_totp bool
	err := row.Scan(&has_totp)
	return has_totp, err
}
