// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_workspaces.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminCountWorkspaceMembers = `-- name: AdminCountWorkspaceMembers :one
SELECT count(*) FROM workspace_memberships WHERE workspace_id = $1
`

func (q *Queries) AdminCountWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountWorkspaceMembers, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetWorkspaceByID = `-- name: AdminGetWorkspaceByID :one
SELECT id, name, slug::text, base_currency::text, cycle_anchor_day, locale, timezone, deleted_at, created_at
FROM workspaces WHERE id = $1
`

type AdminGetWorkspaceByIDRow struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	BaseCurrency   string     `json:"base_currency"`
	CycleAnchorDay int16      `json:"cycle_anchor_day"`
	Locale         string     `json:"locale"`
	Timezone       string     `json:"timezone"`
	DeletedAt      *time.Time `json:"deleted_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

func (q *Queries) AdminGetWorkspaceByID(ctx context.Context, id uuid.UUID) (AdminGetWorkspaceByIDRow, error) {
	row := q.db.QueryRow(ctx, adminGetWorkspaceByID, id)
	var i AdminGetWorkspaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BaseCurrency,
		&i.CycleAnchorDay,
		&i.Locale,
		&i.Timezone,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const adminListWorkspaces = `-- name: AdminListWorkspaces :many
SELECT id, name, slug::text, base_currency::text, cycle_anchor_day, locale, timezone, deleted_at, created_at
FROM workspaces
WHERE ($1::bool OR deleted_at IS NULL)
  AND ($2::text = '' OR name ILIKE $3 OR slug::text ILIKE $3 OR id::text ILIKE $3)
  AND ($4::timestamptz IS NULL OR (created_at, id) < ($4, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type AdminListWorkspacesParams struct {
	IncludeDeleted  bool       `json:"include_deleted"`
	Search          string     `json:"search"`
	SearchPattern   string     `json:"search_pattern"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	QueryLimit      int32      `json:"query_limit"`
}

type AdminListWorkspacesRow struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	BaseCurrency   string     `json:"base_currency"`
	CycleAnchorDay int16      `json:"cycle_anchor_day"`
	Locale         string     `json:"locale"`
	Timezone       string     `json:"timezone"`
	DeletedAt      *time.Time `json:"deleted_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

func (q *Queries) AdminListWorkspaces(ctx context.Context, arg AdminListWorkspacesParams) ([]AdminListWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, adminListWorkspaces,
		arg.IncludeDeleted,
		arg.Search,
		arg.SearchPattern,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListWorkspacesRow{}
	for rows.Next() {
		var i AdminListWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.BaseCurrency,
			&i.CycleAnchorDay,
			&i.Locale,
			&i.Timezone,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
