// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminListAuditEvents = `-- name: AdminListAuditEvents :many
SELECT id, workspace_id, actor_user_id, entity_type, entity_id, action,
       before_jsonb, after_jsonb, occurred_at
FROM audit_events
WHERE ($1::uuid IS NULL OR actor_user_id = $1)
  AND ($2::uuid IS NULL OR workspace_id = $2)
  AND ($3::text = '' OR action LIKE $3 || '%')
  AND ($4::timestamptz IS NULL OR occurred_at >= $4)
  AND ($5::timestamptz IS NULL OR occurred_at <= $5)
  AND ($6::timestamptz IS NULL OR (occurred_at, id) < ($6, $7::uuid))
ORDER BY occurred_at DESC, id DESC
LIMIT $8
`

type AdminListAuditEventsParams struct {
	FilterActorUserID *uuid.UUID `json:"filter_actor_user_id"`
	FilterWorkspaceID *uuid.UUID `json:"filter_workspace_id"`
	FilterAction      string     `json:"filter_action"`
	FilterSince       *time.Time `json:"filter_since"`
	FilterUntil       *time.Time `json:"filter_until"`
	CursorOccurredAt  *time.Time `json:"cursor_occurred_at"`
	CursorID          *uuid.UUID `json:"cursor_id"`
	QueryLimit        int32      `json:"query_limit"`
}

type AdminListAuditEventsRow struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	ActorUserID *uuid.UUID `json:"actor_user_id"`
	EntityType  string     `json:"entity_type"`
	EntityID    uuid.UUID  `json:"entity_id"`
	Action      string     `json:"action"`
	BeforeJsonb []byte     `json:"before_jsonb"`
	AfterJsonb  []byte     `json:"after_jsonb"`
	OccurredAt  time.Time  `json:"occurred_at"`
}

func (q *Queries) AdminListAuditEvents(ctx context.Context, arg AdminListAuditEventsParams) ([]AdminListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, adminListAuditEvents,
		arg.FilterActorUserID,
		arg.FilterWorkspaceID,
		arg.FilterAction,
		arg.FilterSince,
		arg.FilterUntil,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAuditEventsRow{}
	for rows.Next() {
		var i AdminListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorUserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.BeforeJsonb,
			&i.AfterJsonb,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
