// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbq

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    id, workspace_id, actor_user_id, action,
    entity_type, entity_id, before_jsonb, after_jsonb, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
`

type InsertAuditEventParams struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	ActorUserID *uuid.UUID `json:"actor_user_id"`
	Action      string     `json:"action"`
	EntityType  string     `json:"entity_type"`
	EntityID    uuid.UUID  `json:"entity_id"`
	BeforeJsonb []byte     `json:"before_jsonb"`
	AfterJsonb  []byte     `json:"after_jsonb"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeJsonb,
		arg.AfterJsonb,
	)
	return err
}

const insertAuditEventWithRequest = `-- name: InsertAuditEventWithRequest :exec
INSERT INTO audit_events (
    id, workspace_id, actor_user_id, action, entity_type, entity_id,
    before_jsonb, after_jsonb, ip, user_agent
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditEventWithRequestParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID *uuid.UUID  `json:"workspace_id"`
	ActorUserID *uuid.UUID  `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    uuid.UUID   `json:"entity_id"`
	BeforeJsonb []byte      `json:"before_jsonb"`
	AfterJsonb  []byte      `json:"after_jsonb"`
	Ip          *netip.Addr `json:"ip"`
	UserAgent   *string     `json:"user_agent"`
}

func (q *Queries) InsertAuditEventWithRequest(ctx context.Context, arg InsertAuditEventWithRequestParams) error {
	_, err := q.db.Exec(ctx, insertAuditEventWithRequest,
		arg.ID,
		arg.WorkspaceID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeJsonb,
		arg.AfterJsonb,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}
