// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :exec
UPDATE auth_tokens SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeAuthToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeAuthToken, id)
	return err
}

const getAuthTokenForConsume = `-- name: GetAuthTokenForConsume :one
SELECT id, user_id, coalesce(email::text, '')::text AS email, expires_at
FROM auth_tokens
WHERE token_hash = $1 AND purpose = $2 AND consumed_at IS NULL
FOR UPDATE
`

type GetAuthTokenForConsumeParams struct {
	TokenHash []byte `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

type GetAuthTokenForConsumeRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Email     string    `json:"email"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetAuthTokenForConsume(ctx context.Context, arg GetAuthTokenForConsumeParams) (GetAuthTokenForConsumeRow, error) {
	row := q.db.QueryRow(ctx, getAuthTokenForConsume, arg.TokenHash, arg.Purpose)
	var i GetAuthTokenForConsumeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserForPasswordReset = `-- name: GetUserForPasswordReset :one
SELECT u.id, u.email, u.display_name
FROM auth_tokens t JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1 AND t.purpose = $2 AND t.consumed_at IS NULL
`

type GetUserForPasswordResetParams struct {
	TokenHash []byte `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

type GetUserForPasswordResetRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) GetUserForPasswordReset(ctx context.Context, arg GetUserForPasswordResetParams) (GetUserForPasswordResetRow, error) {
	row := q.db.QueryRow(ctx, getUserForPasswordReset, arg.TokenHash, arg.Purpose)
	var i GetUserForPasswordResetRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}

const insertAuthToken = `-- name: InsertAuthToken :exec
INSERT INTO auth_tokens (id, user_id, purpose, token_hash, email, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuthTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Purpose   string    `json:"purpose"`
	TokenHash []byte    `json:"token_hash"`
	Email     *string   `json:"email"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertAuthToken(ctx context.Context, arg InsertAuthTokenParams) error {
	_, err := q.db.Exec(ctx, insertAuthToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}
