// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveCategory = `-- name: ArchiveCategory :execrows
UPDATE categories
SET archived_at = coalesce(archived_at, $1)
WHERE workspace_id = $2 AND id = $3
`

type ArchiveCategoryParams struct {
	Now         *time.Time `json:"now"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ID          uuid.UUID  `json:"id"`
}

func (q *Queries) ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCategory, arg.Now, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const categoryExists = `-- name: CategoryExists :one
SELECT true AS ok FROM categories WHERE workspace_id = $1 AND id = $2
`

type CategoryExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) CategoryExists(ctx context.Context, arg CategoryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryExists, arg.WorkspaceID, arg.ID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, workspace_id, parent_id, name, color, sort_order, archived_at, created_at, updated_at
FROM categories
WHERE workspace_id = $1 AND id = $2
`

type GetCategoryParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.WorkspaceID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (id, workspace_id, parent_id, name, color, sort_order)
VALUES ($1, $2, $3, $4, $5, coalesce($6::int, 0))
RETURNING id, workspace_id, parent_id, name, color, sort_order, archived_at, created_at, updated_at
`

type InsertCategoryParams struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Name        string     `json:"name"`
	Color       *string    `json:"color"`
	SortOrder   *int32     `json:"sort_order"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory,
		arg.ID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Color,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
