// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package dbq

import (
	"context"
)

const sweepDeletedWorkspaces = `-- name: SweepDeletedWorkspaces :many
DELETE FROM workspaces
WHERE deleted_at IS NOT NULL
  AND deleted_at < now() - make_interval(secs => $1::float8)
RETURNING id::text
`

func (q *Queries) SweepDeletedWorkspaces(ctx context.Context, gracePeriodSeconds float64) ([]string, error) {
	rows, err := q.db.Query(ctx, sweepDeletedWorkspaces, gracePeriodSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
