// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corporate_actions.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteCorporateAction = `-- name: DeleteCorporateAction :execrows
DELETE FROM corporate_actions
WHERE id = $1 AND workspace_id = $2
`

type DeleteCorporateActionParams struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteCorporateAction(ctx context.Context, arg DeleteCorporateActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCorporateAction, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCorporateActionForDelete = `-- name: GetCorporateActionForDelete :one
SELECT instrument_id, account_id FROM corporate_actions
WHERE id = $1 AND (workspace_id = $2 OR workspace_id IS NULL)
`

type GetCorporateActionForDeleteParams struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type GetCorporateActionForDeleteRow struct {
	InstrumentID uuid.UUID  `json:"instrument_id"`
	AccountID    *uuid.UUID `json:"account_id"`
}

func (q *Queries) GetCorporateActionForDelete(ctx context.Context, arg GetCorporateActionForDeleteParams) (GetCorporateActionForDeleteRow, error) {
	row := q.db.QueryRow(ctx, getCorporateActionForDelete, arg.ID, arg.WorkspaceID)
	var i GetCorporateActionForDeleteRow
	err := row.Scan(&i.InstrumentID, &i.AccountID)
	return i, err
}

const insertCorporateAction = `-- name: InsertCorporateAction :one
INSERT INTO corporate_actions (
  id, workspace_id, account_id, instrument_id,
  kind, effective_date, payload
) VALUES (
  $1, $2, $3, $4,
  $5::corporate_action_kind, $6, $7::jsonb
)
RETURNING
  id, workspace_id, account_id, instrument_id,
  kind::text, effective_date, payload, applied_at, created_at
`

type InsertCorporateActionParams struct {
	ID            uuid.UUID           `json:"id"`
	WorkspaceID   *uuid.UUID          `json:"workspace_id"`
	AccountID     *uuid.UUID          `json:"account_id"`
	InstrumentID  uuid.UUID           `json:"instrument_id"`
	Kind          CorporateActionKind `json:"kind"`
	EffectiveDate time.Time           `json:"effective_date"`
	Payload       []byte              `json:"payload"`
}

type InsertCorporateActionRow struct {
	ID            uuid.UUID  `json:"id"`
	WorkspaceID   *uuid.UUID `json:"workspace_id"`
	AccountID     *uuid.UUID `json:"account_id"`
	InstrumentID  uuid.UUID  `json:"instrument_id"`
	Kind          string     `json:"kind"`
	EffectiveDate time.Time  `json:"effective_date"`
	Payload       []byte     `json:"payload"`
	AppliedAt     *time.Time `json:"applied_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

func (q *Queries) InsertCorporateAction(ctx context.Context, arg InsertCorporateActionParams) (InsertCorporateActionRow, error) {
	row := q.db.QueryRow(ctx, insertCorporateAction,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Kind,
		arg.EffectiveDate,
		arg.Payload,
	)
	var i InsertCorporateActionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Kind,
		&i.EffectiveDate,
		&i.Payload,
		&i.AppliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCorporateActions = `-- name: ListCorporateActions :many
SELECT
  ca.id, ca.workspace_id, ca.account_id, ca.instrument_id, i.symbol,
  ca.kind::text AS kind, ca.effective_date, ca.payload, ca.applied_at, ca.created_at
FROM corporate_actions ca
JOIN instruments i ON i.id = ca.instrument_id
WHERE ca.instrument_id = $1
  AND (ca.workspace_id IS NULL OR ca.workspace_id = $2)
ORDER BY ca.effective_date DESC, ca.created_at DESC
`

type ListCorporateActionsParams struct {
	InstrumentID uuid.UUID  `json:"instrument_id"`
	WorkspaceID  *uuid.UUID `json:"workspace_id"`
}

type ListCorporateActionsRow struct {
	ID            uuid.UUID  `json:"id"`
	WorkspaceID   *uuid.UUID `json:"workspace_id"`
	AccountID     *uuid.UUID `json:"account_id"`
	InstrumentID  uuid.UUID  `json:"instrument_id"`
	Symbol        string     `json:"symbol"`
	Kind          string     `json:"kind"`
	EffectiveDate time.Time  `json:"effective_date"`
	Payload       []byte     `json:"payload"`
	AppliedAt     *time.Time `json:"applied_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

func (q *Queries) ListCorporateActions(ctx context.Context, arg ListCorporateActionsParams) ([]ListCorporateActionsRow, error) {
	rows, err := q.db.Query(ctx, listCorporateActions, arg.InstrumentID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCorporateActionsRow{}
	for rows.Next() {
		var i ListCorporateActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.InstrumentID,
			&i.Symbol,
			&i.Kind,
			&i.EffectiveDate,
			&i.Payload,
			&i.AppliedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionAccountsForInstrument = `-- name: ListPositionAccountsForInstrument :many
SELECT DISTINCT account_id FROM investment_positions
WHERE workspace_id = $1 AND instrument_id = $2
`

type ListPositionAccountsForInstrumentParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) ListPositionAccountsForInstrument(ctx context.Context, arg ListPositionAccountsForInstrumentParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPositionAccountsForInstrument, arg.WorkspaceID, arg.InstrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var account_id uuid.UUID
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadCorporateActionEvents = `-- name: LoadCorporateActionEvents :many
SELECT kind::text AS kind, effective_date, payload
FROM corporate_actions
WHERE (workspace_id IS NULL OR workspace_id = $1)
  AND (account_id IS NULL OR account_id = $2)
  AND instrument_id = $3
ORDER BY effective_date ASC, id ASC
`

type LoadCorporateActionEventsParams struct {
	WorkspaceID  *uuid.UUID `json:"workspace_id"`
	AccountID    *uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID  `json:"instrument_id"`
}

type LoadCorporateActionEventsRow struct {
	Kind          string    `json:"kind"`
	EffectiveDate time.Time `json:"effective_date"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) LoadCorporateActionEvents(ctx context.Context, arg LoadCorporateActionEventsParams) ([]LoadCorporateActionEventsRow, error) {
	rows, err := q.db.Query(ctx, loadCorporateActionEvents, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadCorporateActionEventsRow{}
	for rows.Next() {
		var i LoadCorporateActionEventsRow
		if err := rows.Scan(&i.Kind, &i.EffectiveDate, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
