// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dividend_events.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDividendEvent = `-- name: DeleteDividendEvent :exec
DELETE FROM dividend_events WHERE workspace_id = $1 AND id = $2
`

type DeleteDividendEventParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) DeleteDividendEvent(ctx context.Context, arg DeleteDividendEventParams) error {
	_, err := q.db.Exec(ctx, deleteDividendEvent, arg.WorkspaceID, arg.ID)
	return err
}

const dividendExists = `-- name: DividendExists :one
SELECT EXISTS(
  SELECT 1 FROM dividend_events
  WHERE workspace_id = $1 AND account_id = $2 AND instrument_id = $3
    AND pay_date = $4
    AND total_amount = $5
)
`

type DividendExistsParams struct {
	WorkspaceID  uuid.UUID      `json:"workspace_id"`
	AccountID    uuid.UUID      `json:"account_id"`
	InstrumentID uuid.UUID      `json:"instrument_id"`
	PayDate      time.Time      `json:"pay_date"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) DividendExists(ctx context.Context, arg DividendExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, dividendExists,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.PayDate,
		arg.TotalAmount,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDividendAccountInstrument = `-- name: GetDividendAccountInstrument :one
SELECT account_id, instrument_id FROM dividend_events
WHERE workspace_id = $1 AND id = $2
`

type GetDividendAccountInstrumentParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

type GetDividendAccountInstrumentRow struct {
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) GetDividendAccountInstrument(ctx context.Context, arg GetDividendAccountInstrumentParams) (GetDividendAccountInstrumentRow, error) {
	row := q.db.QueryRow(ctx, getDividendAccountInstrument, arg.WorkspaceID, arg.ID)
	var i GetDividendAccountInstrumentRow
	err := row.Scan(&i.AccountID, &i.InstrumentID)
	return i, err
}

const insertDividendEvent = `-- name: InsertDividendEvent :one
INSERT INTO dividend_events (
  id, workspace_id, account_id, instrument_id,
  ex_date, pay_date, amount_per_unit, currency, total_amount, tax_withheld
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8, $9, $10
)
RETURNING
  id, workspace_id, account_id, instrument_id,
  ex_date, pay_date, amount_per_unit::text, currency,
  total_amount::text, tax_withheld::text,
  linked_cash_transaction_id, created_at
`

type InsertDividendEventParams struct {
	ID            uuid.UUID      `json:"id"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	InstrumentID  uuid.UUID      `json:"instrument_id"`
	ExDate        time.Time      `json:"ex_date"`
	PayDate       time.Time      `json:"pay_date"`
	AmountPerUnit pgtype.Numeric `json:"amount_per_unit"`
	Currency      string         `json:"currency"`
	TotalAmount   pgtype.Numeric `json:"total_amount"`
	TaxWithheld   pgtype.Numeric `json:"tax_withheld"`
}

type InsertDividendEventRow struct {
	ID                      uuid.UUID  `json:"id"`
	WorkspaceID             uuid.UUID  `json:"workspace_id"`
	AccountID               uuid.UUID  `json:"account_id"`
	InstrumentID            uuid.UUID  `json:"instrument_id"`
	ExDate                  time.Time  `json:"ex_date"`
	PayDate                 time.Time  `json:"pay_date"`
	AmountPerUnit           string     `json:"amount_per_unit"`
	Currency                string     `json:"currency"`
	TotalAmount             string     `json:"total_amount"`
	TaxWithheld             string     `json:"tax_withheld"`
	LinkedCashTransactionID *uuid.UUID `json:"linked_cash_transaction_id"`
	CreatedAt               time.Time  `json:"created_at"`
}

func (q *Queries) InsertDividendEvent(ctx context.Context, arg InsertDividendEventParams) (InsertDividendEventRow, error) {
	row := q.db.QueryRow(ctx, insertDividendEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.ExDate,
		arg.PayDate,
		arg.AmountPerUnit,
		arg.Currency,
		arg.TotalAmount,
		arg.TaxWithheld,
	)
	var i InsertDividendEventRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.InstrumentID,
		&i.ExDate,
		&i.PayDate,
		&i.AmountPerUnit,
		&i.Currency,
		&i.TotalAmount,
		&i.TaxWithheld,
		&i.LinkedCashTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertDividendEventExec = `-- name: InsertDividendEventExec :exec
INSERT INTO dividend_events (
  id, workspace_id, account_id, instrument_id,
  ex_date, pay_date, amount_per_unit, currency, total_amount, tax_withheld
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8, $9, $10
)
`

type InsertDividendEventExecParams struct {
	ID            uuid.UUID      `json:"id"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	InstrumentID  uuid.UUID      `json:"instrument_id"`
	ExDate        time.Time      `json:"ex_date"`
	PayDate       time.Time      `json:"pay_date"`
	AmountPerUnit pgtype.Numeric `json:"amount_per_unit"`
	Currency      string         `json:"currency"`
	TotalAmount   pgtype.Numeric `json:"total_amount"`
	TaxWithheld   pgtype.Numeric `json:"tax_withheld"`
}

func (q *Queries) InsertDividendEventExec(ctx context.Context, arg InsertDividendEventExecParams) error {
	_, err := q.db.Exec(ctx, insertDividendEventExec,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.ExDate,
		arg.PayDate,
		arg.AmountPerUnit,
		arg.Currency,
		arg.TotalAmount,
		arg.TaxWithheld,
	)
	return err
}

const loadDividendEvents = `-- name: LoadDividendEvents :many
SELECT pay_date, total_amount::text, currency
FROM dividend_events
WHERE workspace_id = $1 AND account_id = $2 AND instrument_id = $3
ORDER BY pay_date ASC, id ASC
`

type LoadDividendEventsParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

type LoadDividendEventsRow struct {
	PayDate     time.Time `json:"pay_date"`
	TotalAmount string    `json:"total_amount"`
	Currency    string    `json:"currency"`
}

func (q *Queries) LoadDividendEvents(ctx context.Context, arg LoadDividendEventsParams) ([]LoadDividendEventsRow, error) {
	rows, err := q.db.Query(ctx, loadDividendEvents, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadDividendEventsRow{}
	for rows.Next() {
		var i LoadDividendEventsRow
		if err := rows.Scan(&i.PayDate, &i.TotalAmount, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
