// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixtures.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertTestUser = `-- name: InsertTestUser :exec
INSERT INTO users (id, email, display_name, password_hash, email_verified_at)
VALUES ($1, $2, $3, '$argon2id$stub', $4)
`

type InsertTestUserParams struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
}

func (q *Queries) InsertTestUser(ctx context.Context, arg InsertTestUserParams) error {
	_, err := q.db.Exec(ctx, insertTestUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.EmailVerifiedAt,
	)
	return err
}

const insertTestWorkspace = `-- name: InsertTestWorkspace :exec
INSERT INTO workspaces (id, name, slug, base_currency, cycle_anchor_day, locale, timezone)
VALUES ($1, $2, $3, 'CHF', 1, 'en', 'UTC')
`

type InsertTestWorkspaceParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) InsertTestWorkspace(ctx context.Context, arg InsertTestWorkspaceParams) error {
	_, err := q.db.Exec(ctx, insertTestWorkspace, arg.ID, arg.Name, arg.Slug)
	return err
}

const updateSessionReauthByID = `-- name: UpdateSessionReauthByID :exec
UPDATE sessions SET reauth_at = $1 WHERE id = $2
`

type UpdateSessionReauthByIDParams struct {
	ReauthAt *time.Time `json:"reauth_at"`
	ID       string     `json:"id"`
}

func (q *Queries) UpdateSessionReauthByID(ctx context.Context, arg UpdateSessionReauthByIDParams) error {
	_, err := q.db.Exec(ctx, updateSessionReauthByID, arg.ReauthAt, arg.ID)
	return err
}
