// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountCurrency = `-- name: GetAccountCurrency :one
SELECT currency FROM accounts WHERE workspace_id = $1 AND id = $2
`

type GetAccountCurrencyParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) GetAccountCurrency(ctx context.Context, arg GetAccountCurrencyParams) (string, error) {
	row := q.db.QueryRow(ctx, getAccountCurrency, arg.WorkspaceID, arg.ID)
	var currency string
	err := row.Scan(&currency)
	return currency, err
}

const insertImportAccount = `-- name: InsertImportAccount :exec
INSERT INTO accounts (
  id, workspace_id, name, kind, currency, institution,
  open_date, opening_balance, opening_balance_date,
  include_in_networth, include_in_savings_rate
) VALUES (
  $1, $2, $3, $4::account_kind, $5, $6,
  $7, $8::numeric, $9, true, $10
)
`

type InsertImportAccountParams struct {
	ID                   uuid.UUID      `json:"id"`
	WorkspaceID          uuid.UUID      `json:"workspace_id"`
	Name                 string         `json:"name"`
	Kind                 AccountKind    `json:"kind"`
	Currency             string         `json:"currency"`
	Institution          *string        `json:"institution"`
	OpenDate             time.Time      `json:"open_date"`
	OpeningBalance       pgtype.Numeric `json:"opening_balance"`
	OpeningBalanceDate   time.Time      `json:"opening_balance_date"`
	IncludeInSavingsRate bool           `json:"include_in_savings_rate"`
}

func (q *Queries) InsertImportAccount(ctx context.Context, arg InsertImportAccountParams) error {
	_, err := q.db.Exec(ctx, insertImportAccount,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Kind,
		arg.Currency,
		arg.Institution,
		arg.OpenDate,
		arg.OpeningBalance,
		arg.OpeningBalanceDate,
		arg.IncludeInSavingsRate,
	)
	return err
}

const insertImportBatch = `-- name: InsertImportBatch :exec
INSERT INTO import_batches (
  id, workspace_id, source_kind, file_name, file_hash, status,
  summary, created_by_user_id, started_at, finished_at
) VALUES (
  $1, $2, 'file_upload', $3, $4, 'applied',
  $5::jsonb, $6, $7, $7
)
`

type InsertImportBatchParams struct {
	ID              uuid.UUID  `json:"id"`
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	FileName        *string    `json:"file_name"`
	FileHash        *string    `json:"file_hash"`
	Summary         []byte     `json:"summary"`
	CreatedByUserID *uuid.UUID `json:"created_by_user_id"`
	StartedAt       time.Time  `json:"started_at"`
}

func (q *Queries) InsertImportBatch(ctx context.Context, arg InsertImportBatchParams) error {
	_, err := q.db.Exec(ctx, insertImportBatch,
		arg.ID,
		arg.WorkspaceID,
		arg.FileName,
		arg.FileHash,
		arg.Summary,
		arg.CreatedByUserID,
		arg.StartedAt,
	)
	return err
}

const insertImportTransaction = `-- name: InsertImportTransaction :exec
INSERT INTO transactions (
  id, workspace_id, account_id, status, booked_at, value_at, posted_at,
  amount, currency, counterparty_raw, description, raw
) VALUES (
  $1, $2, $3, 'posted', $4, $5, $6,
  $7::numeric, $8, $9, $10, $11::jsonb
)
`

type InsertImportTransactionParams struct {
	ID              uuid.UUID      `json:"id"`
	WorkspaceID     uuid.UUID      `json:"workspace_id"`
	AccountID       uuid.UUID      `json:"account_id"`
	BookedAt        time.Time      `json:"booked_at"`
	ValueAt         *time.Time     `json:"value_at"`
	PostedAt        *time.Time     `json:"posted_at"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	CounterpartyRaw *string        `json:"counterparty_raw"`
	Description     *string        `json:"description"`
	Raw             []byte         `json:"raw"`
}

func (q *Queries) InsertImportTransaction(ctx context.Context, arg InsertImportTransactionParams) error {
	_, err := q.db.Exec(ctx, insertImportTransaction,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.BookedAt,
		arg.ValueAt,
		arg.PostedAt,
		arg.Amount,
		arg.Currency,
		arg.CounterpartyRaw,
		arg.Description,
		arg.Raw,
	)
	return err
}

const insertSourceRef = `-- name: InsertSourceRef :exec
INSERT INTO source_refs (
  id, workspace_id, entity_type, entity_id, provider,
  import_batch_id, external_id, raw_payload, observed_at
) VALUES (
  $1, $2, 'transaction', $3, $4,
  $5, $6, $7::jsonb, $8
)
`

type InsertSourceRefParams struct {
	ID            uuid.UUID  `json:"id"`
	WorkspaceID   uuid.UUID  `json:"workspace_id"`
	EntityID      uuid.UUID  `json:"entity_id"`
	Provider      *string    `json:"provider"`
	ImportBatchID *uuid.UUID `json:"import_batch_id"`
	ExternalID    *string    `json:"external_id"`
	RawPayload    []byte     `json:"raw_payload"`
	ObservedAt    time.Time  `json:"observed_at"`
}

func (q *Queries) InsertSourceRef(ctx context.Context, arg InsertSourceRefParams) error {
	_, err := q.db.Exec(ctx, insertSourceRef,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityID,
		arg.Provider,
		arg.ImportBatchID,
		arg.ExternalID,
		arg.RawPayload,
		arg.ObservedAt,
	)
	return err
}

const listImportAccountMatches = `-- name: ListImportAccountMatches :many
SELECT id, name, currency, institution, archived_at
FROM accounts
WHERE workspace_id = $1
ORDER BY name
`

type ListImportAccountMatchesRow struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Currency    string     `json:"currency"`
	Institution *string    `json:"institution"`
	ArchivedAt  *time.Time `json:"archived_at"`
}

// Archived accounts are kept in the candidate set so re-importing the
// same file matches the account the user already imported into instead
// of silently creating a duplicate.
func (q *Queries) ListImportAccountMatches(ctx context.Context, workspaceID uuid.UUID) ([]ListImportAccountMatchesRow, error) {
	rows, err := q.db.Query(ctx, listImportAccountMatches, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportAccountMatchesRow{}
	for rows.Next() {
		var i ListImportAccountMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Institution,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadExistingTransactions = `-- name: LoadExistingTransactions :many
SELECT t.id, t.booked_at, t.posted_at, t.amount::text AS amount, t.currency,
       coalesce(t.description, t.counterparty_raw, '')::text AS description,
       sr.external_id AS source_id,
       coalesce(t.raw->>'synthetic' = 'balance_reconcile', false)::bool AS synthetic
FROM transactions t
LEFT JOIN source_refs sr
  ON sr.workspace_id = t.workspace_id
 AND sr.entity_type = 'transaction'
 AND sr.entity_id = t.id
 AND sr.provider = $1
WHERE t.workspace_id = $2
  AND t.account_id = $3
  AND t.booked_at BETWEEN $4 AND $5
  AND t.status <> 'voided'
  AND t.currency = $6
`

type LoadExistingTransactionsParams struct {
	Provider    *string   `json:"provider"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
	DateFrom    time.Time `json:"date_from"`
	DateTo      time.Time `json:"date_to"`
	Currency    string    `json:"currency"`
}

type LoadExistingTransactionsRow struct {
	ID          uuid.UUID  `json:"id"`
	BookedAt    time.Time  `json:"booked_at"`
	PostedAt    *time.Time `json:"posted_at"`
	Amount      string     `json:"amount"`
	Currency    string     `json:"currency"`
	Description string     `json:"description"`
	SourceID    *string    `json:"source_id"`
	Synthetic   bool       `json:"synthetic"`
}

// Load existing transactions in the date range for duplicate/conflict detection.
func (q *Queries) LoadExistingTransactions(ctx context.Context, arg LoadExistingTransactionsParams) ([]LoadExistingTransactionsRow, error) {
	rows, err := q.db.Query(ctx, loadExistingTransactions,
		arg.Provider,
		arg.WorkspaceID,
		arg.AccountID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadExistingTransactionsRow{}
	for rows.Next() {
		var i LoadExistingTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookedAt,
			&i.PostedAt,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.SourceID,
			&i.Synthetic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRealRowsForSynthetic = `-- name: LoadRealRowsForSynthetic :many
SELECT t.id, t.booked_at, t.posted_at, t.amount::text AS amount, t.currency,
       coalesce(t.description, t.counterparty_raw, '')::text AS description
FROM transactions t
JOIN source_refs sr
  ON sr.workspace_id = t.workspace_id
 AND sr.entity_type = 'transaction'
 AND sr.entity_id = t.id
WHERE t.workspace_id = $1
  AND t.account_id = $2
  AND t.status = 'posted'
  AND t.currency = $3
  AND t.booked_at BETWEEN $4::timestamptz AND $5::timestamptz
  AND coalesce(t.raw->>'synthetic', '') <> 'balance_reconcile'
  AND t.id <> $6
  AND ($7::uuid IS NULL OR sr.import_batch_id <> $7::uuid)
`

type LoadRealRowsForSyntheticParams struct {
	WorkspaceID    uuid.UUID  `json:"workspace_id"`
	AccountID      uuid.UUID  `json:"account_id"`
	Currency       string     `json:"currency"`
	DateFrom       time.Time  `json:"date_from"`
	DateTo         time.Time  `json:"date_to"`
	ExcludeID      uuid.UUID  `json:"exclude_id"`
	ExcludeBatchID *uuid.UUID `json:"exclude_batch_id"`
}

type LoadRealRowsForSyntheticRow struct {
	ID          uuid.UUID  `json:"id"`
	BookedAt    time.Time  `json:"booked_at"`
	PostedAt    *time.Time `json:"posted_at"`
	Amount      string     `json:"amount"`
	Currency    string     `json:"currency"`
	Description string     `json:"description"`
}

// Load real (non-synthetic) rows near a synthetic for residual-explained check.
// Only considers rows from a different import batch than the synthetic itself.
func (q *Queries) LoadRealRowsForSynthetic(ctx context.Context, arg LoadRealRowsForSyntheticParams) ([]LoadRealRowsForSyntheticRow, error) {
	rows, err := q.db.Query(ctx, loadRealRowsForSynthetic,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Currency,
		arg.DateFrom,
		arg.DateTo,
		arg.ExcludeID,
		arg.ExcludeBatchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadRealRowsForSyntheticRow{}
	for rows.Next() {
		var i LoadRealRowsForSyntheticRow
		if err := rows.Scan(
			&i.ID,
			&i.BookedAt,
			&i.PostedAt,
			&i.Amount,
			&i.Currency,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadSyntheticCandidates = `-- name: LoadSyntheticCandidates :many
SELECT t.id, t.booked_at, t.posted_at, t.amount::text AS amount, t.currency,
       coalesce(t.raw->>'synthetic_residual', t.amount::text)::text AS residual,
       coalesce(t.raw->>'gap_start_date', '')::text AS gap_start_date,
       sr.import_batch_id
FROM transactions t
LEFT JOIN source_refs sr
  ON sr.workspace_id = t.workspace_id
 AND sr.entity_type = 'transaction'
 AND sr.entity_id = t.id
WHERE t.workspace_id = $1
  AND t.account_id = $2
  AND t.status = 'posted'
  AND t.raw->>'synthetic' = 'balance_reconcile'
  AND t.booked_at BETWEEN $3::timestamptz AND $4::timestamptz
`

type LoadSyntheticCandidatesParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
	DateFrom    time.Time `json:"date_from"`
	DateTo      time.Time `json:"date_to"`
}

type LoadSyntheticCandidatesRow struct {
	ID            uuid.UUID  `json:"id"`
	BookedAt      time.Time  `json:"booked_at"`
	PostedAt      *time.Time `json:"posted_at"`
	Amount        string     `json:"amount"`
	Currency      string     `json:"currency"`
	Residual      string     `json:"residual"`
	GapStartDate  string     `json:"gap_start_date"`
	ImportBatchID *uuid.UUID `json:"import_batch_id"`
}

// Scan synthetic balance-reconcile rows for potential retirement.
// gap_start_date is the consolidated row date that established the previous
// balance for this synthetic; together with booked_at it bounds the interval
// where the missing real transaction must have occurred. Older synthetics
// (pre-#TBD) didn't store this and fall back to NULL.
func (q *Queries) LoadSyntheticCandidates(ctx context.Context, arg LoadSyntheticCandidatesParams) ([]LoadSyntheticCandidatesRow, error) {
	rows, err := q.db.Query(ctx, loadSyntheticCandidates,
		arg.WorkspaceID,
		arg.AccountID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadSyntheticCandidatesRow{}
	for rows.Next() {
		var i LoadSyntheticCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.BookedAt,
			&i.PostedAt,
			&i.Amount,
			&i.Currency,
			&i.Residual,
			&i.GapStartDate,
			&i.ImportBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveAccount = `-- name: UnarchiveAccount :exec
UPDATE accounts
SET archived_at = null
WHERE workspace_id = $1 AND id = $2 AND archived_at IS NOT NULL
`

type UnarchiveAccountParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

// Opt-in reactivate: clear archived_at when the user explicitly
// asked to resurface this account. No-op for non-archived rows.
func (q *Queries) UnarchiveAccount(ctx context.Context, arg UnarchiveAccountParams) error {
	_, err := q.db.Exec(ctx, unarchiveAccount, arg.WorkspaceID, arg.ID)
	return err
}

const voidTransaction = `-- name: VoidTransaction :exec
UPDATE transactions SET status = 'voided' WHERE id = $1 AND workspace_id = $2
`

type VoidTransactionParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) VoidTransaction(ctx context.Context, arg VoidTransactionParams) error {
	_, err := q.db.Exec(ctx, voidTransaction, arg.ID, arg.WorkspaceID)
	return err
}
