// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instruments.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findInstrumentByISIN = `-- name: FindInstrumentByISIN :one
SELECT id, symbol, isin, name, asset_class::text AS asset_class, currency, exchange, active, created_at, updated_at
FROM instruments WHERE isin = $1
`

type FindInstrumentByISINRow struct {
	ID         uuid.UUID `json:"id"`
	Symbol     string    `json:"symbol"`
	Isin       *string   `json:"isin"`
	Name       string    `json:"name"`
	AssetClass string    `json:"asset_class"`
	Currency   string    `json:"currency"`
	Exchange   *string   `json:"exchange"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) FindInstrumentByISIN(ctx context.Context, isin *string) (FindInstrumentByISINRow, error) {
	row := q.db.QueryRow(ctx, findInstrumentByISIN, isin)
	var i FindInstrumentByISINRow
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Isin,
		&i.Name,
		&i.AssetClass,
		&i.Currency,
		&i.Exchange,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findInstrumentBySymbolAndExchange = `-- name: FindInstrumentBySymbolAndExchange :one
SELECT id, symbol, isin, name, asset_class::text AS asset_class, currency, exchange, active, created_at, updated_at
FROM instruments WHERE symbol = $1 AND exchange = $2 AND isin IS NULL
`

type FindInstrumentBySymbolAndExchangeParams struct {
	Symbol   string  `json:"symbol"`
	Exchange *string `json:"exchange"`
}

type FindInstrumentBySymbolAndExchangeRow struct {
	ID         uuid.UUID `json:"id"`
	Symbol     string    `json:"symbol"`
	Isin       *string   `json:"isin"`
	Name       string    `json:"name"`
	AssetClass string    `json:"asset_class"`
	Currency   string    `json:"currency"`
	Exchange   *string   `json:"exchange"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) FindInstrumentBySymbolAndExchange(ctx context.Context, arg FindInstrumentBySymbolAndExchangeParams) (FindInstrumentBySymbolAndExchangeRow, error) {
	row := q.db.QueryRow(ctx, findInstrumentBySymbolAndExchange, arg.Symbol, arg.Exchange)
	var i FindInstrumentBySymbolAndExchangeRow
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Isin,
		&i.Name,
		&i.AssetClass,
		&i.Currency,
		&i.Exchange,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findInstrumentBySymbolOnly = `-- name: FindInstrumentBySymbolOnly :one
SELECT id, symbol, isin, name, asset_class::text AS asset_class, currency, exchange, active, created_at, updated_at
FROM instruments WHERE symbol = $1 AND exchange IS NULL AND isin IS NULL
LIMIT 1
`

type FindInstrumentBySymbolOnlyRow struct {
	ID         uuid.UUID `json:"id"`
	Symbol     string    `json:"symbol"`
	Isin       *string   `json:"isin"`
	Name       string    `json:"name"`
	AssetClass string    `json:"asset_class"`
	Currency   string    `json:"currency"`
	Exchange   *string   `json:"exchange"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) FindInstrumentBySymbolOnly(ctx context.Context, symbol string) (FindInstrumentBySymbolOnlyRow, error) {
	row := q.db.QueryRow(ctx, findInstrumentBySymbolOnly, symbol)
	var i FindInstrumentBySymbolOnlyRow
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Isin,
		&i.Name,
		&i.AssetClass,
		&i.Currency,
		&i.Exchange,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstrumentByID = `-- name: GetInstrumentByID :one
SELECT id, symbol, isin, name, asset_class::text AS asset_class, currency, exchange, active, created_at, updated_at
FROM instruments WHERE id = $1
`

type GetInstrumentByIDRow struct {
	ID         uuid.UUID `json:"id"`
	Symbol     string    `json:"symbol"`
	Isin       *string   `json:"isin"`
	Name       string    `json:"name"`
	AssetClass string    `json:"asset_class"`
	Currency   string    `json:"currency"`
	Exchange   *string   `json:"exchange"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) GetInstrumentByID(ctx context.Context, id uuid.UUID) (GetInstrumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getInstrumentByID, id)
	var i GetInstrumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Isin,
		&i.Name,
		&i.AssetClass,
		&i.Currency,
		&i.Exchange,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstrumentBySymbol = `-- name: GetInstrumentBySymbol :one
SELECT id, symbol, isin, name, asset_class::text AS asset_class, currency, exchange, active, created_at, updated_at
FROM instruments WHERE upper(symbol) = upper($1)
ORDER BY active DESC, updated_at DESC
LIMIT 1
`

type GetInstrumentBySymbolRow struct {
	ID         uuid.UUID `json:"id"`
	Symbol     string    `json:"symbol"`
	Isin       *string   `json:"isin"`
	Name       string    `json:"name"`
	AssetClass string    `json:"asset_class"`
	Currency   string    `json:"currency"`
	Exchange   *string   `json:"exchange"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) GetInstrumentBySymbol(ctx context.Context, symbol interface{}) (GetInstrumentBySymbolRow, error) {
	row := q.db.QueryRow(ctx, getInstrumentBySymbol, symbol)
	var i GetInstrumentBySymbolRow
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Isin,
		&i.Name,
		&i.AssetClass,
		&i.Currency,
		&i.Exchange,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstrumentCurrency = `-- name: GetInstrumentCurrency :one
SELECT currency FROM instruments WHERE id = $1
`

func (q *Queries) GetInstrumentCurrency(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getInstrumentCurrency, id)
	var currency string
	err := row.Scan(&currency)
	return currency, err
}

const insertInstrument = `-- name: InsertInstrument :one
INSERT INTO instruments (id, symbol, isin, name, asset_class, currency, exchange)
VALUES ($1, $2, $3, $4, $5::asset_class, $6, $7)
ON CONFLICT DO NOTHING
RETURNING id, symbol, isin, name, asset_class::text AS asset_class, currency, exchange, active, created_at, updated_at
`

type InsertInstrumentParams struct {
	ID         uuid.UUID  `json:"id"`
	Symbol     string     `json:"symbol"`
	Isin       *string    `json:"isin"`
	Name       string     `json:"name"`
	AssetClass AssetClass `json:"asset_class"`
	Currency   string     `json:"currency"`
	Exchange   *string    `json:"exchange"`
}

type InsertInstrumentRow struct {
	ID         uuid.UUID `json:"id"`
	Symbol     string    `json:"symbol"`
	Isin       *string   `json:"isin"`
	Name       string    `json:"name"`
	AssetClass string    `json:"asset_class"`
	Currency   string    `json:"currency"`
	Exchange   *string   `json:"exchange"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) InsertInstrument(ctx context.Context, arg InsertInstrumentParams) (InsertInstrumentRow, error) {
	row := q.db.QueryRow(ctx, insertInstrument,
		arg.ID,
		arg.Symbol,
		arg.Isin,
		arg.Name,
		arg.AssetClass,
		arg.Currency,
		arg.Exchange,
	)
	var i InsertInstrumentRow
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Isin,
		&i.Name,
		&i.AssetClass,
		&i.Currency,
		&i.Exchange,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchInstruments = `-- name: SearchInstruments :many
SELECT id, symbol, isin, name, asset_class::text AS asset_class, currency, exchange, active, created_at, updated_at
FROM instruments
WHERE active AND (symbol ILIKE $1 || '%' OR name ILIKE '%' || $1 || '%' OR isin ILIKE $1 || '%')
ORDER BY CASE WHEN upper(symbol) = upper($1) THEN 0 ELSE 1 END, symbol
LIMIT $2
`

type SearchInstrumentsParams struct {
	Query      *string `json:"query"`
	MaxResults int32   `json:"max_results"`
}

type SearchInstrumentsRow struct {
	ID         uuid.UUID `json:"id"`
	Symbol     string    `json:"symbol"`
	Isin       *string   `json:"isin"`
	Name       string    `json:"name"`
	AssetClass string    `json:"asset_class"`
	Currency   string    `json:"currency"`
	Exchange   *string   `json:"exchange"`
	Active     bool      `json:"active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) SearchInstruments(ctx context.Context, arg SearchInstrumentsParams) ([]SearchInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, searchInstruments, arg.Query, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchInstrumentsRow{}
	for rows.Next() {
		var i SearchInstrumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Isin,
			&i.Name,
			&i.AssetClass,
			&i.Currency,
			&i.Exchange,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
