// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investment_accounts.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findBrokerageAccount = `-- name: FindBrokerageAccount :one
SELECT a.id, a.name
FROM accounts a
WHERE a.workspace_id = $1 AND a.kind = 'brokerage'
  AND a.archived_at IS NULL
  AND (
    a.currency = $2
    OR coalesce(a.institution, '') ILIKE '%' || $3 || '%'
    OR coalesce(a.nickname, '') ILIKE '%' || $3 || '%'
    OR a.name ILIKE '%' || $3 || '%'
  )
ORDER BY CASE WHEN a.currency = $2 THEN 0 ELSE 1 END,
         a.created_at ASC
LIMIT 1
`

type FindBrokerageAccountParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Currency    string    `json:"currency"`
	SourceLabel *string   `json:"source_label"`
}

type FindBrokerageAccountRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) FindBrokerageAccount(ctx context.Context, arg FindBrokerageAccountParams) (FindBrokerageAccountRow, error) {
	row := q.db.QueryRow(ctx, findBrokerageAccount, arg.WorkspaceID, arg.Currency, arg.SourceLabel)
	var i FindBrokerageAccountRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAccountKind = `-- name: GetAccountKind :one
SELECT kind::text FROM accounts WHERE workspace_id = $1 AND id = $2
`

type GetAccountKindParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) GetAccountKind(ctx context.Context, arg GetAccountKindParams) (string, error) {
	row := q.db.QueryRow(ctx, getAccountKind, arg.WorkspaceID, arg.ID)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getWorkspaceBaseCurrency = `-- name: GetWorkspaceBaseCurrency :one
SELECT base_currency FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceBaseCurrency(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBaseCurrency, id)
	var base_currency string
	err := row.Scan(&base_currency)
	return base_currency, err
}

const insertBrokerageAccount = `-- name: InsertBrokerageAccount :exec
INSERT INTO accounts (
  id, workspace_id, name, kind, currency, institution,
  open_date, opening_balance, opening_balance_date,
  include_in_networth, include_in_savings_rate
) VALUES (
  $1, $2, $3, 'brokerage'::account_kind, $4, $5,
  $6, 0, $6,
  true, false
)
`

type InsertBrokerageAccountParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Currency    string    `json:"currency"`
	Institution *string   `json:"institution"`
	OpenDate    time.Time `json:"open_date"`
}

func (q *Queries) InsertBrokerageAccount(ctx context.Context, arg InsertBrokerageAccountParams) error {
	_, err := q.db.Exec(ctx, insertBrokerageAccount,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Currency,
		arg.Institution,
		arg.OpenDate,
	)
	return err
}

const insertBrokerageOpeningSnapshot = `-- name: InsertBrokerageOpeningSnapshot :exec
INSERT INTO account_balance_snapshots (
  id, workspace_id, account_id, as_of, balance, currency, source
) VALUES (
  $1, $2, $3, $4, 0, $5, 'opening'
)
`

type InsertBrokerageOpeningSnapshotParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
	AsOf        time.Time `json:"as_of"`
	Currency    string    `json:"currency"`
}

func (q *Queries) InsertBrokerageOpeningSnapshot(ctx context.Context, arg InsertBrokerageOpeningSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertBrokerageOpeningSnapshot,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.AsOf,
		arg.Currency,
	)
	return err
}

const insertInvestmentAccount = `-- name: InsertInvestmentAccount :exec
INSERT INTO investment_accounts (account_id, workspace_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertInvestmentAccountParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) InsertInvestmentAccount(ctx context.Context, arg InsertInvestmentAccountParams) error {
	_, err := q.db.Exec(ctx, insertInvestmentAccount, arg.AccountID, arg.WorkspaceID)
	return err
}

const investmentAccountExists = `-- name: InvestmentAccountExists :one
SELECT EXISTS(SELECT 1 FROM investment_accounts WHERE workspace_id = $1 AND account_id = $2)
`

type InvestmentAccountExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AccountID   uuid.UUID `json:"account_id"`
}

func (q *Queries) InvestmentAccountExists(ctx context.Context, arg InvestmentAccountExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, investmentAccountExists, arg.WorkspaceID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
