// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investment_positions.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInvestmentPosition = `-- name: DeleteInvestmentPosition :exec
DELETE FROM investment_positions
WHERE workspace_id = $1 AND account_id = $2 AND instrument_id = $3
`

type DeleteInvestmentPositionParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) DeleteInvestmentPosition(ctx context.Context, arg DeleteInvestmentPositionParams) error {
	_, err := q.db.Exec(ctx, deleteInvestmentPosition, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	return err
}

const deleteLotConsumptionsForPosition = `-- name: DeleteLotConsumptionsForPosition :exec
DELETE FROM investment_lot_consumptions lc
WHERE lc.workspace_id = $1
  AND lc.lot_id IN (
    SELECT l.id FROM investment_lots l
    WHERE l.workspace_id = $1 AND l.account_id = $2 AND l.instrument_id = $3
  )
`

type DeleteLotConsumptionsForPositionParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) DeleteLotConsumptionsForPosition(ctx context.Context, arg DeleteLotConsumptionsForPositionParams) error {
	_, err := q.db.Exec(ctx, deleteLotConsumptionsForPosition, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	return err
}

const deleteLotsForPosition = `-- name: DeleteLotsForPosition :exec
DELETE FROM investment_lots WHERE workspace_id = $1 AND account_id = $2 AND instrument_id = $3
`

type DeleteLotsForPositionParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) DeleteLotsForPosition(ctx context.Context, arg DeleteLotsForPositionParams) error {
	_, err := q.db.Exec(ctx, deleteLotsForPosition, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	return err
}

const insertInvestmentLot = `-- name: InsertInvestmentLot :exec
INSERT INTO investment_lots (
  id, workspace_id, account_id, instrument_id,
  acquired_at, quantity_opening, quantity_remaining,
  cost_basis_per_unit, currency, source_trade_id, closed_at
) VALUES ($1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10, $11)
`

type InsertInvestmentLotParams struct {
	ID                uuid.UUID      `json:"id"`
	WorkspaceID       uuid.UUID      `json:"workspace_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	InstrumentID      uuid.UUID      `json:"instrument_id"`
	AcquiredAt        time.Time      `json:"acquired_at"`
	QuantityOpening   pgtype.Numeric `json:"quantity_opening"`
	QuantityRemaining pgtype.Numeric `json:"quantity_remaining"`
	CostBasisPerUnit  pgtype.Numeric `json:"cost_basis_per_unit"`
	Currency          string         `json:"currency"`
	SourceTradeID     *uuid.UUID     `json:"source_trade_id"`
	ClosedAt          *time.Time     `json:"closed_at"`
}

func (q *Queries) InsertInvestmentLot(ctx context.Context, arg InsertInvestmentLotParams) error {
	_, err := q.db.Exec(ctx, insertInvestmentLot,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.AcquiredAt,
		arg.QuantityOpening,
		arg.QuantityRemaining,
		arg.CostBasisPerUnit,
		arg.Currency,
		arg.SourceTradeID,
		arg.ClosedAt,
	)
	return err
}

const insertLotConsumption = `-- name: InsertLotConsumption :exec
INSERT INTO investment_lot_consumptions (
  id, workspace_id, lot_id, sell_trade_id,
  quantity_consumed, realised_gain, currency, consumed_at
) VALUES ($1, $2, $3, $4,
  $5, $6, $7, $8)
`

type InsertLotConsumptionParams struct {
	ID               uuid.UUID      `json:"id"`
	WorkspaceID      uuid.UUID      `json:"workspace_id"`
	LotID            uuid.UUID      `json:"lot_id"`
	SellTradeID      uuid.UUID      `json:"sell_trade_id"`
	QuantityConsumed pgtype.Numeric `json:"quantity_consumed"`
	RealisedGain     pgtype.Numeric `json:"realised_gain"`
	Currency         string         `json:"currency"`
	ConsumedAt       time.Time      `json:"consumed_at"`
}

func (q *Queries) InsertLotConsumption(ctx context.Context, arg InsertLotConsumptionParams) error {
	_, err := q.db.Exec(ctx, insertLotConsumption,
		arg.ID,
		arg.WorkspaceID,
		arg.LotID,
		arg.SellTradeID,
		arg.QuantityConsumed,
		arg.RealisedGain,
		arg.Currency,
		arg.ConsumedAt,
	)
	return err
}

const listInvestmentPositions = `-- name: ListInvestmentPositions :many
SELECT
  p.account_id, p.instrument_id, p.workspace_id,
  i.symbol, i.name, i.asset_class::text AS asset_class, i.currency AS instrument_currency,
  a.currency AS account_currency,
  p.quantity::text AS quantity, p.average_cost::text AS average_cost,
  (p.quantity * p.average_cost)::text AS cost_basis_total,
  p.realised_pnl::text AS realised_pnl,
  coalesce(div.total, 0)::text AS dividends_received,
  coalesce(fees.total, 0)::text AS fees_paid,
  last_trade.last_date AS last_trade_date,
  coalesce(lp.price::text, '') AS last_price,
  coalesce(lp.as_of, '0001-01-01 00:00:00+00'::timestamptz) AS last_price_at
FROM investment_positions p
JOIN instruments i ON i.id = p.instrument_id
JOIN accounts a ON a.id = p.account_id
LEFT JOIN LATERAL (
  SELECT coalesce(sum(total_amount), 0) AS total
  FROM dividend_events d
  WHERE d.workspace_id = p.workspace_id
    AND d.account_id = p.account_id
    AND d.instrument_id = p.instrument_id
) div ON true
LEFT JOIN LATERAL (
  SELECT coalesce(sum(fee_amount), 0) AS total
  FROM investment_trades t
  WHERE t.workspace_id = p.workspace_id
    AND t.account_id = p.account_id
    AND t.instrument_id = p.instrument_id
) fees ON true
LEFT JOIN LATERAL (
  SELECT max(trade_date) AS last_date
  FROM investment_trades t
  WHERE t.workspace_id = p.workspace_id
    AND t.account_id = p.account_id
    AND t.instrument_id = p.instrument_id
) last_trade ON true
LEFT JOIN LATERAL (
  SELECT price, as_of
  FROM instrument_prices
  WHERE instrument_id = p.instrument_id
  ORDER BY as_of DESC
  LIMIT 1
) lp ON true
WHERE p.workspace_id = $1
  AND ($2::uuid IS NULL OR p.account_id = $2::uuid)
  AND ($3::uuid IS NULL OR p.instrument_id = $3::uuid)
  AND (NOT $4::bool OR p.quantity > 0)
  AND (NOT $5::bool OR p.quantity = 0)
  AND (
    $6::text = ''
    OR lower(i.symbol) LIKE $7::text
    OR lower(i.name) LIKE $7::text
  )
ORDER BY (p.quantity * coalesce(lp.price, p.average_cost)) DESC, i.symbol
`

type ListInvestmentPositionsParams struct {
	WorkspaceID   uuid.UUID  `json:"workspace_id"`
	AccountID     *uuid.UUID `json:"account_id"`
	InstrumentID  *uuid.UUID `json:"instrument_id"`
	OpenOnly      bool       `json:"open_only"`
	ClosedOnly    bool       `json:"closed_only"`
	Search        string     `json:"search"`
	SearchPattern string     `json:"search_pattern"`
}

type ListInvestmentPositionsRow struct {
	AccountID          uuid.UUID   `json:"account_id"`
	InstrumentID       uuid.UUID   `json:"instrument_id"`
	WorkspaceID        uuid.UUID   `json:"workspace_id"`
	Symbol             string      `json:"symbol"`
	Name               string      `json:"name"`
	AssetClass         string      `json:"asset_class"`
	InstrumentCurrency string      `json:"instrument_currency"`
	AccountCurrency    string      `json:"account_currency"`
	Quantity           string      `json:"quantity"`
	AverageCost        string      `json:"average_cost"`
	CostBasisTotal     string      `json:"cost_basis_total"`
	RealisedPnl        string      `json:"realised_pnl"`
	DividendsReceived  string      `json:"dividends_received"`
	FeesPaid           string      `json:"fees_paid"`
	LastTradeDate      interface{} `json:"last_trade_date"`
	LastPrice          interface{} `json:"last_price"`
	LastPriceAt        time.Time   `json:"last_price_at"`
}

func (q *Queries) ListInvestmentPositions(ctx context.Context, arg ListInvestmentPositionsParams) ([]ListInvestmentPositionsRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentPositions,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.OpenOnly,
		arg.ClosedOnly,
		arg.Search,
		arg.SearchPattern,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvestmentPositionsRow{}
	for rows.Next() {
		var i ListInvestmentPositionsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.InstrumentID,
			&i.WorkspaceID,
			&i.Symbol,
			&i.Name,
			&i.AssetClass,
			&i.InstrumentCurrency,
			&i.AccountCurrency,
			&i.Quantity,
			&i.AverageCost,
			&i.CostBasisTotal,
			&i.RealisedPnl,
			&i.DividendsReceived,
			&i.FeesPaid,
			&i.LastTradeDate,
			&i.LastPrice,
			&i.LastPriceAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPositionInstruments = `-- name: ListOpenPositionInstruments :many
SELECT DISTINCT i.id, i.symbol
FROM investment_positions p
JOIN instruments i ON i.id = p.instrument_id
WHERE p.workspace_id = $1 AND p.quantity > 0
`

type ListOpenPositionInstrumentsRow struct {
	ID     uuid.UUID `json:"id"`
	Symbol string    `json:"symbol"`
}

func (q *Queries) ListOpenPositionInstruments(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenPositionInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, listOpenPositionInstruments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenPositionInstrumentsRow{}
	for rows.Next() {
		var i ListOpenPositionInstrumentsRow
		if err := rows.Scan(&i.ID, &i.Symbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPositionInstrumentsWithPrice = `-- name: ListOpenPositionInstrumentsWithPrice :many
SELECT DISTINCT ON (p.instrument_id)
  p.instrument_id, i.symbol, lp.as_of::timestamptz AS last_price_as_of
FROM investment_positions p
JOIN instruments i ON i.id = p.instrument_id
LEFT JOIN LATERAL (
  SELECT as_of FROM instrument_prices
  WHERE instrument_id = p.instrument_id
  ORDER BY as_of DESC
  LIMIT 1
) lp ON true
WHERE p.workspace_id = $1 AND p.quantity > 0 AND i.active
ORDER BY p.instrument_id
`

type ListOpenPositionInstrumentsWithPriceRow struct {
	InstrumentID  uuid.UUID `json:"instrument_id"`
	Symbol        string    `json:"symbol"`
	LastPriceAsOf time.Time `json:"last_price_as_of"`
}

func (q *Queries) ListOpenPositionInstrumentsWithPrice(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenPositionInstrumentsWithPriceRow, error) {
	rows, err := q.db.Query(ctx, listOpenPositionInstrumentsWithPrice, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenPositionInstrumentsWithPriceRow{}
	for rows.Next() {
		var i ListOpenPositionInstrumentsWithPriceRow
		if err := rows.Scan(&i.InstrumentID, &i.Symbol, &i.LastPriceAsOf); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTouchedInvestmentPairs = `-- name: ListTouchedInvestmentPairs :many
SELECT DISTINCT account_id, instrument_id
FROM investment_trades
WHERE investment_trades.workspace_id = $1
UNION
SELECT DISTINCT account_id, instrument_id
FROM dividend_events
WHERE dividend_events.workspace_id = $1
`

type ListTouchedInvestmentPairsRow struct {
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) ListTouchedInvestmentPairs(ctx context.Context, workspaceID uuid.UUID) ([]ListTouchedInvestmentPairsRow, error) {
	rows, err := q.db.Query(ctx, listTouchedInvestmentPairs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTouchedInvestmentPairsRow{}
	for rows.Next() {
		var i ListTouchedInvestmentPairsRow
		if err := rows.Scan(&i.AccountID, &i.InstrumentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInvestmentPosition = `-- name: UpsertInvestmentPosition :exec
INSERT INTO investment_positions AS ip (
  account_id, instrument_id, workspace_id,
  quantity, average_cost, realised_pnl, currency, refreshed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (account_id, instrument_id) DO UPDATE SET
  quantity = excluded.quantity,
  average_cost = excluded.average_cost,
  realised_pnl = excluded.realised_pnl,
  currency = excluded.currency,
  refreshed_at = excluded.refreshed_at
`

type UpsertInvestmentPositionParams struct {
	AccountID    uuid.UUID      `json:"account_id"`
	InstrumentID uuid.UUID      `json:"instrument_id"`
	WorkspaceID  uuid.UUID      `json:"workspace_id"`
	Quantity     pgtype.Numeric `json:"quantity"`
	AverageCost  pgtype.Numeric `json:"average_cost"`
	RealisedPnl  pgtype.Numeric `json:"realised_pnl"`
	Currency     string         `json:"currency"`
	RefreshedAt  time.Time      `json:"refreshed_at"`
}

func (q *Queries) UpsertInvestmentPosition(ctx context.Context, arg UpsertInvestmentPositionParams) error {
	_, err := q.db.Exec(ctx, upsertInvestmentPosition,
		arg.AccountID,
		arg.InstrumentID,
		arg.WorkspaceID,
		arg.Quantity,
		arg.AverageCost,
		arg.RealisedPnl,
		arg.Currency,
		arg.RefreshedAt,
	)
	return err
}
