// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investment_trades.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInvestmentTrade = `-- name: DeleteInvestmentTrade :exec
DELETE FROM investment_trades WHERE workspace_id = $1 AND id = $2
`

type DeleteInvestmentTradeParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) DeleteInvestmentTrade(ctx context.Context, arg DeleteInvestmentTradeParams) error {
	_, err := q.db.Exec(ctx, deleteInvestmentTrade, arg.WorkspaceID, arg.ID)
	return err
}

const getInvestmentTrade = `-- name: GetInvestmentTrade :one
SELECT
  t.id, t.workspace_id, t.account_id, t.instrument_id, i.symbol,
  t.side::text AS side, t.quantity::text AS quantity, t.price::text AS price, t.currency,
  t.fee_amount::text AS fee_amount, t.fee_currency, t.trade_date, t.settle_date,
  t.linked_cash_transaction_id, t.created_at, t.updated_at
FROM investment_trades t
JOIN instruments i ON i.id = t.instrument_id
WHERE t.workspace_id = $1 AND t.id = $2
`

type GetInvestmentTradeParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

type GetInvestmentTradeRow struct {
	ID                      uuid.UUID  `json:"id"`
	WorkspaceID             uuid.UUID  `json:"workspace_id"`
	AccountID               uuid.UUID  `json:"account_id"`
	InstrumentID            uuid.UUID  `json:"instrument_id"`
	Symbol                  string     `json:"symbol"`
	Side                    string     `json:"side"`
	Quantity                string     `json:"quantity"`
	Price                   string     `json:"price"`
	Currency                string     `json:"currency"`
	FeeAmount               string     `json:"fee_amount"`
	FeeCurrency             string     `json:"fee_currency"`
	TradeDate               time.Time  `json:"trade_date"`
	SettleDate              *time.Time `json:"settle_date"`
	LinkedCashTransactionID *uuid.UUID `json:"linked_cash_transaction_id"`
	CreatedAt               time.Time  `json:"created_at"`
	UpdatedAt               time.Time  `json:"updated_at"`
}

func (q *Queries) GetInvestmentTrade(ctx context.Context, arg GetInvestmentTradeParams) (GetInvestmentTradeRow, error) {
	row := q.db.QueryRow(ctx, getInvestmentTrade, arg.WorkspaceID, arg.ID)
	var i GetInvestmentTradeRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.Currency,
		&i.FeeAmount,
		&i.FeeCurrency,
		&i.TradeDate,
		&i.SettleDate,
		&i.LinkedCashTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTradeAccountInstrument = `-- name: GetTradeAccountInstrument :one
SELECT account_id, instrument_id FROM investment_trades
WHERE workspace_id = $1 AND id = $2
`

type GetTradeAccountInstrumentParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

type GetTradeAccountInstrumentRow struct {
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) GetTradeAccountInstrument(ctx context.Context, arg GetTradeAccountInstrumentParams) (GetTradeAccountInstrumentRow, error) {
	row := q.db.QueryRow(ctx, getTradeAccountInstrument, arg.WorkspaceID, arg.ID)
	var i GetTradeAccountInstrumentRow
	err := row.Scan(&i.AccountID, &i.InstrumentID)
	return i, err
}

const insertInvestmentTrade = `-- name: InsertInvestmentTrade :one
INSERT INTO investment_trades (
  id, workspace_id, account_id, instrument_id, side,
  quantity, price, currency, fee_amount, fee_currency,
  trade_date, settle_date
) VALUES (
  $1, $2, $3, $4, $5::trade_side,
  $6, $7, $8, $9, $10,
  $11, $12
)
RETURNING
  id, workspace_id, account_id, instrument_id,
  side::text, quantity::text, price::text, currency,
  fee_amount::text, fee_currency, trade_date, settle_date,
  linked_cash_transaction_id, created_at, updated_at
`

type InsertInvestmentTradeParams struct {
	ID           uuid.UUID      `json:"id"`
	WorkspaceID  uuid.UUID      `json:"workspace_id"`
	AccountID    uuid.UUID      `json:"account_id"`
	InstrumentID uuid.UUID      `json:"instrument_id"`
	Side         TradeSide      `json:"side"`
	Quantity     pgtype.Numeric `json:"quantity"`
	Price        pgtype.Numeric `json:"price"`
	Currency     string         `json:"currency"`
	FeeAmount    pgtype.Numeric `json:"fee_amount"`
	FeeCurrency  string         `json:"fee_currency"`
	TradeDate    time.Time      `json:"trade_date"`
	SettleDate   *time.Time     `json:"settle_date"`
}

type InsertInvestmentTradeRow struct {
	ID                      uuid.UUID  `json:"id"`
	WorkspaceID             uuid.UUID  `json:"workspace_id"`
	AccountID               uuid.UUID  `json:"account_id"`
	InstrumentID            uuid.UUID  `json:"instrument_id"`
	Side                    string     `json:"side"`
	Quantity                string     `json:"quantity"`
	Price                   string     `json:"price"`
	Currency                string     `json:"currency"`
	FeeAmount               string     `json:"fee_amount"`
	FeeCurrency             string     `json:"fee_currency"`
	TradeDate               time.Time  `json:"trade_date"`
	SettleDate              *time.Time `json:"settle_date"`
	LinkedCashTransactionID *uuid.UUID `json:"linked_cash_transaction_id"`
	CreatedAt               time.Time  `json:"created_at"`
	UpdatedAt               time.Time  `json:"updated_at"`
}

func (q *Queries) InsertInvestmentTrade(ctx context.Context, arg InsertInvestmentTradeParams) (InsertInvestmentTradeRow, error) {
	row := q.db.QueryRow(ctx, insertInvestmentTrade,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Side,
		arg.Quantity,
		arg.Price,
		arg.Currency,
		arg.FeeAmount,
		arg.FeeCurrency,
		arg.TradeDate,
		arg.SettleDate,
	)
	var i InsertInvestmentTradeRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.Currency,
		&i.FeeAmount,
		&i.FeeCurrency,
		&i.TradeDate,
		&i.SettleDate,
		&i.LinkedCashTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInvestmentTradeExec = `-- name: InsertInvestmentTradeExec :exec
INSERT INTO investment_trades (
  id, workspace_id, account_id, instrument_id, side,
  quantity, price, currency, fee_amount, fee_currency,
  trade_date, settle_date
) VALUES (
  $1, $2, $3, $4, $5::trade_side,
  $6, $7, $8, $9, $10,
  $11, $12
)
`

type InsertInvestmentTradeExecParams struct {
	ID           uuid.UUID      `json:"id"`
	WorkspaceID  uuid.UUID      `json:"workspace_id"`
	AccountID    uuid.UUID      `json:"account_id"`
	InstrumentID uuid.UUID      `json:"instrument_id"`
	Side         TradeSide      `json:"side"`
	Quantity     pgtype.Numeric `json:"quantity"`
	Price        pgtype.Numeric `json:"price"`
	Currency     string         `json:"currency"`
	FeeAmount    pgtype.Numeric `json:"fee_amount"`
	FeeCurrency  string         `json:"fee_currency"`
	TradeDate    time.Time      `json:"trade_date"`
	SettleDate   *time.Time     `json:"settle_date"`
}

func (q *Queries) InsertInvestmentTradeExec(ctx context.Context, arg InsertInvestmentTradeExecParams) error {
	_, err := q.db.Exec(ctx, insertInvestmentTradeExec,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Side,
		arg.Quantity,
		arg.Price,
		arg.Currency,
		arg.FeeAmount,
		arg.FeeCurrency,
		arg.TradeDate,
		arg.SettleDate,
	)
	return err
}

const listInvestmentTrades = `-- name: ListInvestmentTrades :many
SELECT
  t.id, t.workspace_id, t.account_id, t.instrument_id, i.symbol,
  t.side::text AS side, t.quantity::text AS quantity, t.price::text AS price, t.currency,
  t.fee_amount::text AS fee_amount, t.fee_currency, t.trade_date, t.settle_date,
  t.linked_cash_transaction_id, t.created_at, t.updated_at
FROM investment_trades t
JOIN instruments i ON i.id = t.instrument_id
WHERE t.workspace_id = $1
  AND ($2::uuid IS NULL OR t.account_id = $2::uuid)
  AND ($3::uuid IS NULL OR t.instrument_id = $3::uuid)
ORDER BY t.trade_date DESC, t.id DESC
LIMIT 1000
`

type ListInvestmentTradesParams struct {
	WorkspaceID  uuid.UUID  `json:"workspace_id"`
	AccountID    *uuid.UUID `json:"account_id"`
	InstrumentID *uuid.UUID `json:"instrument_id"`
}

type ListInvestmentTradesRow struct {
	ID                      uuid.UUID  `json:"id"`
	WorkspaceID             uuid.UUID  `json:"workspace_id"`
	AccountID               uuid.UUID  `json:"account_id"`
	InstrumentID            uuid.UUID  `json:"instrument_id"`
	Symbol                  string     `json:"symbol"`
	Side                    string     `json:"side"`
	Quantity                string     `json:"quantity"`
	Price                   string     `json:"price"`
	Currency                string     `json:"currency"`
	FeeAmount               string     `json:"fee_amount"`
	FeeCurrency             string     `json:"fee_currency"`
	TradeDate               time.Time  `json:"trade_date"`
	SettleDate              *time.Time `json:"settle_date"`
	LinkedCashTransactionID *uuid.UUID `json:"linked_cash_transaction_id"`
	CreatedAt               time.Time  `json:"created_at"`
	UpdatedAt               time.Time  `json:"updated_at"`
}

func (q *Queries) ListInvestmentTrades(ctx context.Context, arg ListInvestmentTradesParams) ([]ListInvestmentTradesRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentTrades, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvestmentTradesRow{}
	for rows.Next() {
		var i ListInvestmentTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.InstrumentID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.FeeAmount,
			&i.FeeCurrency,
			&i.TradeDate,
			&i.SettleDate,
			&i.LinkedCashTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadTradeEvents = `-- name: LoadTradeEvents :many
SELECT id, side::text AS side, trade_date, quantity::text AS quantity, price::text AS price, fee_amount::text AS fee_amount, currency
FROM investment_trades
WHERE workspace_id = $1 AND account_id = $2 AND instrument_id = $3
ORDER BY trade_date ASC, id ASC
`

type LoadTradeEventsParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

type LoadTradeEventsRow struct {
	ID        uuid.UUID `json:"id"`
	Side      string    `json:"side"`
	TradeDate time.Time `json:"trade_date"`
	Quantity  string    `json:"quantity"`
	Price     string    `json:"price"`
	FeeAmount string    `json:"fee_amount"`
	Currency  string    `json:"currency"`
}

func (q *Queries) LoadTradeEvents(ctx context.Context, arg LoadTradeEventsParams) ([]LoadTradeEventsRow, error) {
	rows, err := q.db.Query(ctx, loadTradeEvents, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadTradeEventsRow{}
	for rows.Next() {
		var i LoadTradeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Side,
			&i.TradeDate,
			&i.Quantity,
			&i.Price,
			&i.FeeAmount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tradeExists = `-- name: TradeExists :one
SELECT EXISTS(
  SELECT 1 FROM investment_trades
  WHERE workspace_id = $1 AND account_id = $2 AND instrument_id = $3
    AND side = $4::trade_side
    AND trade_date = $5
    AND quantity = $6
    AND price = $7
)
`

type TradeExistsParams struct {
	WorkspaceID  uuid.UUID      `json:"workspace_id"`
	AccountID    uuid.UUID      `json:"account_id"`
	InstrumentID uuid.UUID      `json:"instrument_id"`
	Side         TradeSide      `json:"side"`
	TradeDate    time.Time      `json:"trade_date"`
	Quantity     pgtype.Numeric `json:"quantity"`
	Price        pgtype.Numeric `json:"price"`
}

func (q *Queries) TradeExists(ctx context.Context, arg TradeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tradeExists,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Side,
		arg.TradeDate,
		arg.Quantity,
		arg.Price,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
