// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investment_positions.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInvestmentPosition = `-- name: DeleteInvestmentPosition :exec
DELETE FROM investment_positions
WHERE workspace_id = $1 AND account_id = $2 AND instrument_id = $3
`

type DeleteInvestmentPositionParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) DeleteInvestmentPosition(ctx context.Context, arg DeleteInvestmentPositionParams) error {
	_, err := q.db.Exec(ctx, deleteInvestmentPosition, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	return err
}

const deleteLotConsumptionsForPosition = `-- name: DeleteLotConsumptionsForPosition :exec
DELETE FROM investment_lot_consumptions lc
WHERE lc.workspace_id = $1
  AND lc.lot_id IN (
    SELECT l.id FROM investment_lots l
    WHERE l.workspace_id = $1 AND l.account_id = $2 AND l.instrument_id = $3
  )
`

type DeleteLotConsumptionsForPositionParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) DeleteLotConsumptionsForPosition(ctx context.Context, arg DeleteLotConsumptionsForPositionParams) error {
	_, err := q.db.Exec(ctx, deleteLotConsumptionsForPosition, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	return err
}

const deleteLotsForPosition = `-- name: DeleteLotsForPosition :exec
DELETE FROM investment_lots WHERE workspace_id = $1 AND account_id = $2 AND instrument_id = $3
`

type DeleteLotsForPositionParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	AccountID    uuid.UUID `json:"account_id"`
	InstrumentID uuid.UUID `json:"instrument_id"`
}

func (q *Queries) DeleteLotsForPosition(ctx context.Context, arg DeleteLotsForPositionParams) error {
	_, err := q.db.Exec(ctx, deleteLotsForPosition, arg.WorkspaceID, arg.AccountID, arg.InstrumentID)
	return err
}

const insertInvestmentLot = `-- name: InsertInvestmentLot :exec
INSERT INTO investment_lots (
  id, workspace_id, account_id, instrument_id,
  acquired_at, quantity_opening, quantity_remaining,
  cost_basis_per_unit, currency, source_trade_id, closed_at
) VALUES ($1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10, $11)
`

type InsertInvestmentLotParams struct {
	ID                uuid.UUID      `json:"id"`
	WorkspaceID       uuid.UUID      `json:"workspace_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	InstrumentID      uuid.UUID      `json:"instrument_id"`
	AcquiredAt        time.Time      `json:"acquired_at"`
	QuantityOpening   pgtype.Numeric `json:"quantity_opening"`
	QuantityRemaining pgtype.Numeric `json:"quantity_remaining"`
	CostBasisPerUnit  pgtype.Numeric `json:"cost_basis_per_unit"`
	Currency          string         `json:"currency"`
	SourceTradeID     *uuid.UUID     `json:"source_trade_id"`
	ClosedAt          *time.Time     `json:"closed_at"`
}

func (q *Queries) InsertInvestmentLot(ctx context.Context, arg InsertInvestmentLotParams) error {
	_, err := q.db.Exec(ctx, insertInvestmentLot,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.InstrumentID,
		arg.AcquiredAt,
		arg.QuantityOpening,
		arg.QuantityRemaining,
		arg.CostBasisPerUnit,
		arg.Currency,
		arg.SourceTradeID,
		arg.ClosedAt,
	)
	return err
}

const insertLotConsumption = `-- name: InsertLotConsumption :exec
INSERT INTO investment_lot_consumptions (
  id, workspace_id, lot_id, sell_trade_id,
  quantity_consumed, realised_gain, currency, consumed_at
) VALUES ($1, $2, $3, $4,
  $5, $6, $7, $8)
`

type InsertLotConsumptionParams struct {
	ID               uuid.UUID      `json:"id"`
	WorkspaceID      uuid.UUID      `json:"workspace_id"`
	LotID            uuid.UUID      `json:"lot_id"`
	SellTradeID      uuid.UUID      `json:"sell_trade_id"`
	QuantityConsumed pgtype.Numeric `json:"quantity_consumed"`
	RealisedGain     pgtype.Numeric `json:"realised_gain"`
	Currency         string         `json:"currency"`
	ConsumedAt       time.Time      `json:"consumed_at"`
}

func (q *Queries) InsertLotConsumption(ctx context.Context, arg InsertLotConsumptionParams) error {
	_, err := q.db.Exec(ctx, insertLotConsumption,
		arg.ID,
		arg.WorkspaceID,
		arg.LotID,
		arg.SellTradeID,
		arg.QuantityConsumed,
		arg.RealisedGain,
		arg.Currency,
		arg.ConsumedAt,
	)
	return err
}

const listOpenPositionInstruments = `-- name: ListOpenPositionInstruments :many
SELECT DISTINCT i.id, i.symbol
FROM investment_positions p
JOIN instruments i ON i.id = p.instrument_id
WHERE p.workspace_id = $1 AND p.quantity > 0
`

type ListOpenPositionInstrumentsRow struct {
	ID     uuid.UUID `json:"id"`
	Symbol string    `json:"symbol"`
}

func (q *Queries) ListOpenPositionInstruments(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenPositionInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, listOpenPositionInstruments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenPositionInstrumentsRow{}
	for rows.Next() {
		var i ListOpenPositionInstrumentsRow
		if err := rows.Scan(&i.ID, &i.Symbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPositionInstrumentsWithPrice = `-- name: ListOpenPositionInstrumentsWithPrice :many
SELECT DISTINCT ON (p.instrument_id)
  p.instrument_id, i.symbol, lp.as_of::timestamptz AS last_price_as_of
FROM investment_positions p
JOIN instruments i ON i.id = p.instrument_id
LEFT JOIN LATERAL (
  SELECT as_of FROM instrument_prices
  WHERE instrument_id = p.instrument_id
  ORDER BY as_of DESC
  LIMIT 1
) lp ON true
WHERE p.workspace_id = $1 AND p.quantity > 0 AND i.active
ORDER BY p.instrument_id
`

type ListOpenPositionInstrumentsWithPriceRow struct {
	InstrumentID  uuid.UUID `json:"instrument_id"`
	Symbol        string    `json:"symbol"`
	LastPriceAsOf time.Time `json:"last_price_as_of"`
}

func (q *Queries) ListOpenPositionInstrumentsWithPrice(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenPositionInstrumentsWithPriceRow, error) {
	rows, err := q.db.Query(ctx, listOpenPositionInstrumentsWithPrice, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenPositionInstrumentsWithPriceRow{}
	for rows.Next() {
		var i ListOpenPositionInstrumentsWithPriceRow
		if err := rows.Scan(&i.InstrumentID, &i.Symbol, &i.LastPriceAsOf); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInvestmentPosition = `-- name: UpsertInvestmentPosition :exec
INSERT INTO investment_positions AS ip (
  account_id, instrument_id, workspace_id,
  quantity, average_cost, currency, refreshed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (account_id, instrument_id) DO UPDATE SET
  quantity = excluded.quantity,
  average_cost = excluded.average_cost,
  currency = excluded.currency,
  refreshed_at = excluded.refreshed_at
`

type UpsertInvestmentPositionParams struct {
	AccountID    uuid.UUID      `json:"account_id"`
	InstrumentID uuid.UUID      `json:"instrument_id"`
	WorkspaceID  uuid.UUID      `json:"workspace_id"`
	Quantity     pgtype.Numeric `json:"quantity"`
	AverageCost  pgtype.Numeric `json:"average_cost"`
	Currency     string         `json:"currency"`
	RefreshedAt  time.Time      `json:"refreshed_at"`
}

func (q *Queries) UpsertInvestmentPosition(ctx context.Context, arg UpsertInvestmentPositionParams) error {
	_, err := q.db.Exec(ctx, upsertInvestmentPosition,
		arg.AccountID,
		arg.InstrumentID,
		arg.WorkspaceID,
		arg.Quantity,
		arg.AverageCost,
		arg.Currency,
		arg.RefreshedAt,
	)
	return err
}
