// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market_prices.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const lookupCachedFXRate = `-- name: LookupCachedFXRate :one
SELECT rate
FROM fx_rates
WHERE base_currency = $1 AND quote_currency = $2 AND as_of <= $3
ORDER BY as_of DESC
LIMIT 1
`

type LookupCachedFXRateParams struct {
	BaseCurrency  string    `json:"base_currency"`
	QuoteCurrency string    `json:"quote_currency"`
	AsOf          time.Time `json:"as_of"`
}

func (q *Queries) LookupCachedFXRate(ctx context.Context, arg LookupCachedFXRateParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, lookupCachedFXRate, arg.BaseCurrency, arg.QuoteCurrency, arg.AsOf)
	var rate pgtype.Numeric
	err := row.Scan(&rate)
	return rate, err
}

const lookupCachedLatestPrice = `-- name: LookupCachedLatestPrice :one
SELECT as_of, price, currency, source::text AS source
FROM instrument_prices
WHERE instrument_id = $1
ORDER BY as_of DESC
LIMIT 1
`

type LookupCachedLatestPriceRow struct {
	AsOf     time.Time      `json:"as_of"`
	Price    pgtype.Numeric `json:"price"`
	Currency string         `json:"currency"`
	Source   string         `json:"source"`
}

func (q *Queries) LookupCachedLatestPrice(ctx context.Context, instrumentID uuid.UUID) (LookupCachedLatestPriceRow, error) {
	row := q.db.QueryRow(ctx, lookupCachedLatestPrice, instrumentID)
	var i LookupCachedLatestPriceRow
	err := row.Scan(
		&i.AsOf,
		&i.Price,
		&i.Currency,
		&i.Source,
	)
	return i, err
}

const lookupCachedPriceRange = `-- name: LookupCachedPriceRange :many
SELECT as_of, price, currency, source::text AS source
FROM instrument_prices
WHERE instrument_id = $1 AND as_of >= $2 AND as_of <= $3
ORDER BY as_of ASC
`

type LookupCachedPriceRangeParams struct {
	InstrumentID uuid.UUID `json:"instrument_id"`
	FromDate     time.Time `json:"from_date"`
	ToDate       time.Time `json:"to_date"`
}

type LookupCachedPriceRangeRow struct {
	AsOf     time.Time      `json:"as_of"`
	Price    pgtype.Numeric `json:"price"`
	Currency string         `json:"currency"`
	Source   string         `json:"source"`
}

func (q *Queries) LookupCachedPriceRange(ctx context.Context, arg LookupCachedPriceRangeParams) ([]LookupCachedPriceRangeRow, error) {
	rows, err := q.db.Query(ctx, lookupCachedPriceRange, arg.InstrumentID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupCachedPriceRangeRow{}
	for rows.Next() {
		var i LookupCachedPriceRangeRow
		if err := rows.Scan(
			&i.AsOf,
			&i.Price,
			&i.Currency,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const persistFXRate = `-- name: PersistFXRate :exec
INSERT INTO fx_rates (id, base_currency, quote_currency, as_of, rate, source)
VALUES ($1, $2, $3, $4, $5, $6::fx_source)
ON CONFLICT (base_currency, quote_currency, as_of, source) DO NOTHING
`

type PersistFXRateParams struct {
	ID            uuid.UUID      `json:"id"`
	BaseCurrency  string         `json:"base_currency"`
	QuoteCurrency string         `json:"quote_currency"`
	AsOf          time.Time      `json:"as_of"`
	Rate          pgtype.Numeric `json:"rate"`
	Source        FxSource       `json:"source"`
}

func (q *Queries) PersistFXRate(ctx context.Context, arg PersistFXRateParams) error {
	_, err := q.db.Exec(ctx, persistFXRate,
		arg.ID,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.AsOf,
		arg.Rate,
		arg.Source,
	)
	return err
}

const persistInstrumentPrice = `-- name: PersistInstrumentPrice :exec
INSERT INTO instrument_prices (id, instrument_id, as_of, price, currency, source)
VALUES ($1, $2, $3, $4, $5, $6::price_source)
ON CONFLICT (instrument_id, as_of, source) DO NOTHING
`

type PersistInstrumentPriceParams struct {
	ID           uuid.UUID      `json:"id"`
	InstrumentID uuid.UUID      `json:"instrument_id"`
	AsOf         time.Time      `json:"as_of"`
	Price        pgtype.Numeric `json:"price"`
	Currency     string         `json:"currency"`
	Source       PriceSource    `json:"source"`
}

func (q *Queries) PersistInstrumentPrice(ctx context.Context, arg PersistInstrumentPriceParams) error {
	_, err := q.db.Exec(ctx, persistInstrumentPrice,
		arg.ID,
		arg.InstrumentID,
		arg.AsOf,
		arg.Price,
		arg.Currency,
		arg.Source,
	)
	return err
}
