// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package dbq

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const bumpMFAChallengeAttempts = `-- name: BumpMFAChallengeAttempts :one
UPDATE auth_mfa_challenges
SET attempts = attempts + 1,
    consumed_at = CASE WHEN attempts + 1 >= 10 THEN $2 ELSE consumed_at END
WHERE id = $1
RETURNING attempts
`

type BumpMFAChallengeAttemptsParams struct {
	ID         uuid.UUID  `json:"id"`
	ConsumedAt *time.Time `json:"consumed_at"`
}

func (q *Queries) BumpMFAChallengeAttempts(ctx context.Context, arg BumpMFAChallengeAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpMFAChallengeAttempts, arg.ID, arg.ConsumedAt)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const consumeMFAChallenge = `-- name: ConsumeMFAChallenge :execrows
UPDATE auth_mfa_challenges SET consumed_at = $2
WHERE id = $1 AND consumed_at IS NULL
`

type ConsumeMFAChallengeParams struct {
	ID         uuid.UUID  `json:"id"`
	ConsumedAt *time.Time `json:"consumed_at"`
}

func (q *Queries) ConsumeMFAChallenge(ctx context.Context, arg ConsumeMFAChallengeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeMFAChallenge, arg.ID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOpenMFAChallengesByUser = `-- name: ConsumeOpenMFAChallengesByUser :exec
UPDATE auth_mfa_challenges SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeOpenMFAChallengesByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOpenMFAChallengesByUser, userID)
	return err
}

const getMFAChallengeByID = `-- name: GetMFAChallengeByID :one
SELECT id, user_id, ip::text AS ip, user_agent, created_at, expires_at,
       consumed_at, attempts, coalesce(webauthn_state, '{}'::jsonb) AS webauthn_state
FROM auth_mfa_challenges
WHERE id = $1
`

type GetMFAChallengeByIDRow struct {
	ID            uuid.UUID  `json:"id"`
	UserID        uuid.UUID  `json:"user_id"`
	Ip            string     `json:"ip"`
	UserAgent     string     `json:"user_agent"`
	CreatedAt     time.Time  `json:"created_at"`
	ExpiresAt     time.Time  `json:"expires_at"`
	ConsumedAt    *time.Time `json:"consumed_at"`
	Attempts      int32      `json:"attempts"`
	WebauthnState []byte     `json:"webauthn_state"`
}

func (q *Queries) GetMFAChallengeByID(ctx context.Context, id uuid.UUID) (GetMFAChallengeByIDRow, error) {
	row := q.db.QueryRow(ctx, getMFAChallengeByID, id)
	var i GetMFAChallengeByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Attempts,
		&i.WebauthnState,
	)
	return i, err
}

const getMFAStatus = `-- name: GetMFAStatus :one
SELECT
    exists(SELECT 1 FROM totp_credentials tc WHERE tc.user_id = $1 AND tc.verified_at IS NOT NULL) AS totp_enrolled,
    (SELECT count(*) FROM webauthn_credentials wc WHERE wc.user_id = $1) AS passkey_count,
    (SELECT count(*) FROM auth_recovery_codes rc WHERE rc.user_id = $1 AND rc.consumed_at IS NULL) AS remaining_recovery_codes
`

type GetMFAStatusRow struct {
	TotpEnrolled           bool  `json:"totp_enrolled"`
	PasskeyCount           int64 `json:"passkey_count"`
	RemainingRecoveryCodes int64 `json:"remaining_recovery_codes"`
}

func (q *Queries) GetMFAStatus(ctx context.Context, userID uuid.UUID) (GetMFAStatusRow, error) {
	row := q.db.QueryRow(ctx, getMFAStatus, userID)
	var i GetMFAStatusRow
	err := row.Scan(&i.TotpEnrolled, &i.PasskeyCount, &i.RemainingRecoveryCodes)
	return i, err
}

const hasMFAEnrolled = `-- name: HasMFAEnrolled :one
SELECT exists(SELECT 1 FROM totp_credentials tc WHERE tc.user_id = $1 AND tc.verified_at IS NOT NULL)
    OR exists(SELECT 1 FROM webauthn_credentials wc WHERE wc.user_id = $1) AS has_mfa
`

func (q *Queries) HasMFAEnrolled(ctx context.Context, userID uuid.UUID) (*bool, error) {
	row := q.db.QueryRow(ctx, hasMFAEnrolled, userID)
	var has_mfa *bool
	err := row.Scan(&has_mfa)
	return has_mfa, err
}

const insertMFAChallenge = `-- name: InsertMFAChallenge :exec
INSERT INTO auth_mfa_challenges
    (id, user_id, ip, user_agent, created_at, expires_at, webauthn_state)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertMFAChallengeParams struct {
	ID            uuid.UUID  `json:"id"`
	UserID        uuid.UUID  `json:"user_id"`
	Ip            netip.Addr `json:"ip"`
	UserAgent     string     `json:"user_agent"`
	CreatedAt     time.Time  `json:"created_at"`
	ExpiresAt     time.Time  `json:"expires_at"`
	WebauthnState []byte     `json:"webauthn_state"`
}

func (q *Queries) InsertMFAChallenge(ctx context.Context, arg InsertMFAChallengeParams) error {
	_, err := q.db.Exec(ctx, insertMFAChallenge,
		arg.ID,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.WebauthnState,
	)
	return err
}

const updateMFAChallengeWebAuthnState = `-- name: UpdateMFAChallengeWebAuthnState :exec
UPDATE auth_mfa_challenges SET webauthn_state = $2 WHERE id = $1
`

type UpdateMFAChallengeWebAuthnStateParams struct {
	ID            uuid.UUID `json:"id"`
	WebauthnState []byte    `json:"webauthn_state"`
}

func (q *Queries) UpdateMFAChallengeWebAuthnState(ctx context.Context, arg UpdateMFAChallengeWebAuthnStateParams) error {
	_, err := q.db.Exec(ctx, updateMFAChallengeWebAuthnState, arg.ID, arg.WebauthnState)
	return err
}
