// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_invites.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPlatformInviteByTokenHash = `-- name: GetPlatformInviteByTokenHash :one
SELECT id, email, token_hash, created_by, created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by FROM platform_invites WHERE token_hash = $1
`

func (q *Queries) GetPlatformInviteByTokenHash(ctx context.Context, tokenHash []byte) (PlatformInvite, error) {
	row := q.db.QueryRow(ctx, getPlatformInviteByTokenHash, tokenHash)
	var i PlatformInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getPlatformInviteForAccept = `-- name: GetPlatformInviteForAccept :one
SELECT id, email, token_hash, expires_at, revoked_at, accepted_at
FROM platform_invites
WHERE token_hash = $1
FOR UPDATE
`

type GetPlatformInviteForAcceptRow struct {
	ID         uuid.UUID  `json:"id"`
	Email      *string    `json:"email"`
	TokenHash  []byte     `json:"token_hash"`
	ExpiresAt  time.Time  `json:"expires_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	AcceptedAt *time.Time `json:"accepted_at"`
}

func (q *Queries) GetPlatformInviteForAccept(ctx context.Context, tokenHash []byte) (GetPlatformInviteForAcceptRow, error) {
	row := q.db.QueryRow(ctx, getPlatformInviteForAccept, tokenHash)
	var i GetPlatformInviteForAcceptRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getPlatformInviteForRevoke = `-- name: GetPlatformInviteForRevoke :one
SELECT id, created_by, revoked_at, accepted_at
FROM platform_invites
WHERE id = $1
FOR UPDATE
`

type GetPlatformInviteForRevokeRow struct {
	ID         uuid.UUID  `json:"id"`
	CreatedBy  uuid.UUID  `json:"created_by"`
	RevokedAt  *time.Time `json:"revoked_at"`
	AcceptedAt *time.Time `json:"accepted_at"`
}

func (q *Queries) GetPlatformInviteForRevoke(ctx context.Context, id uuid.UUID) (GetPlatformInviteForRevokeRow, error) {
	row := q.db.QueryRow(ctx, getPlatformInviteForRevoke, id)
	var i GetPlatformInviteForRevokeRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const insertPlatformInvite = `-- name: InsertPlatformInvite :one
INSERT INTO platform_invites (id, email, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, token_hash, created_by, created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by
`

type InsertPlatformInviteParams struct {
	ID        uuid.UUID `json:"id"`
	Email     *string   `json:"email"`
	TokenHash []byte    `json:"token_hash"`
	CreatedBy uuid.UUID `json:"created_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertPlatformInvite(ctx context.Context, arg InsertPlatformInviteParams) (PlatformInvite, error) {
	row := q.db.QueryRow(ctx, insertPlatformInvite,
		arg.ID,
		arg.Email,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i PlatformInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const listPlatformInvitesActive = `-- name: ListPlatformInvitesActive :many
SELECT id, email, token_hash, created_by, created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by FROM platform_invites
WHERE accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListPlatformInvitesActive(ctx context.Context) ([]PlatformInvite, error) {
	rows, err := q.db.Query(ctx, listPlatformInvitesActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformInvite{}
	for rows.Next() {
		var i PlatformInvite
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformInvitesAll = `-- name: ListPlatformInvitesAll :many
SELECT id, email, token_hash, created_by, created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by FROM platform_invites
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPlatformInvitesAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlatformInvitesAll(ctx context.Context, arg ListPlatformInvitesAllParams) ([]PlatformInvite, error) {
	rows, err := q.db.Query(ctx, listPlatformInvitesAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformInvite{}
	for rows.Next() {
		var i PlatformInvite
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlatformInviteAccepted = `-- name: MarkPlatformInviteAccepted :exec
UPDATE platform_invites
SET accepted_at = now(), accepted_by = $2
WHERE id = $1
`

type MarkPlatformInviteAcceptedParams struct {
	ID         uuid.UUID  `json:"id"`
	AcceptedBy *uuid.UUID `json:"accepted_by"`
}

func (q *Queries) MarkPlatformInviteAccepted(ctx context.Context, arg MarkPlatformInviteAcceptedParams) error {
	_, err := q.db.Exec(ctx, markPlatformInviteAccepted, arg.ID, arg.AcceptedBy)
	return err
}

const markPlatformInviteRevoked = `-- name: MarkPlatformInviteRevoked :exec
UPDATE platform_invites
SET revoked_at = now(), revoked_by = $2
WHERE id = $1
`

type MarkPlatformInviteRevokedParams struct {
	ID        uuid.UUID  `json:"id"`
	RevokedBy *uuid.UUID `json:"revoked_by"`
}

func (q *Queries) MarkPlatformInviteRevoked(ctx context.Context, arg MarkPlatformInviteRevokedParams) error {
	_, err := q.db.Exec(ctx, markPlatformInviteRevoked, arg.ID, arg.RevokedBy)
	return err
}
