// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptWorkspaceInvite(ctx context.Context, id uuid.UUID) error
	// Detects whether an account already contains higher-fidelity savings-
	// statement events. Used to make MMF summary retirement order-independent:
	// a consolidated import that follows a savings-statement import should
	// still void its newly-emitted summary rows, just like the reverse order.
	AccountHasSavingsStatementRows(ctx context.Context, arg AccountHasSavingsStatementRowsParams) (bool, error)
	AcquireFirstRunLock(ctx context.Context, pgAdvisoryXactLock int64) error
	AcquireUserMembershipLock(ctx context.Context, dollar_1 string) error
	AcquireWorkspaceMembershipLock(ctx context.Context, dollar_1 string) error
	AdminCountAdmins(ctx context.Context) (int64, error)
	AdminCountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error)
	AdminCountWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	AdminGetUserDetail(ctx context.Context, id uuid.UUID) (AdminGetUserDetailRow, error)
	AdminGetUserIsAdminForUpdate(ctx context.Context, id uuid.UUID) (bool, error)
	AdminGetWorkspaceByID(ctx context.Context, id uuid.UUID) (AdminGetWorkspaceByIDRow, error)
	AdminListAuditEvents(ctx context.Context, arg AdminListAuditEventsParams) ([]AdminListAuditEventsRow, error)
	AdminListUserActiveSessions(ctx context.Context, userID uuid.UUID) ([]AdminListUserActiveSessionsRow, error)
	AdminListUserMemberships(ctx context.Context, userID uuid.UUID) ([]AdminListUserMembershipsRow, error)
	AdminListUserPasskeys(ctx context.Context, userID uuid.UUID) ([]AdminListUserPasskeysRow, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	AdminListWorkspaces(ctx context.Context, arg AdminListWorkspacesParams) ([]AdminListWorkspacesRow, error)
	AdminSetUserAdmin(ctx context.Context, arg AdminSetUserAdminParams) error
	AdminUserHasTOTP(ctx context.Context, userID uuid.UUID) (bool, error)
	ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (int64, error)
	ArchiveTag(ctx context.Context, arg ArchiveTagParams) (int64, error)
	// Move the opening-balance anchor back when a later import lands rows that
	// pre-date the existing one (e.g. a savings-statement import covering a
	// period before the account's first consolidated-MMF interest event).
	// Without this, the balance query's `booked_at >= opening_balance_date`
	// filter silently excludes the early rows from the displayed balance even
	// though they were inserted. Only shifts when @new_date is strictly
	// earlier — a no-op if already covered.
	BackfillAccountOpeningDate(ctx context.Context, arg BackfillAccountOpeningDateParams) error
	// Companion to BackfillAccountOpeningDate. The balance query reads from
	// the latest snapshot's as_of when present, so updating only the account
	// column is insufficient — the snapshot has to move with it.
	BackfillOpeningSnapshot(ctx context.Context, arg BackfillOpeningSnapshotParams) error
	BumpMFAChallengeAttempts(ctx context.Context, arg BumpMFAChallengeAttemptsParams) (int32, error)
	BumpTOTPLastUsedStep(ctx context.Context, arg BumpTOTPLastUsedStepParams) (int64, error)
	CategoryExists(ctx context.Context, arg CategoryExistsParams) (bool, error)
	CheckEmailExistsExcludingUser(ctx context.Context, arg CheckEmailExistsExcludingUserParams) (bool, error)
	CheckIsWorkspaceOwner(ctx context.Context, arg CheckIsWorkspaceOwnerParams) (bool, error)
	ClearAccountGroupMembership(ctx context.Context, arg ClearAccountGroupMembershipParams) error
	ConfirmTOTPCredential(ctx context.Context, arg ConfirmTOTPCredentialParams) error
	ConsumeAuthToken(ctx context.Context, id uuid.UUID) error
	ConsumeMFAChallenge(ctx context.Context, arg ConsumeMFAChallengeParams) (int64, error)
	ConsumeOpenMFAChallengesByUser(ctx context.Context, userID uuid.UUID) error
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) error
	CountUnconsumedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserMemberships(ctx context.Context, userID uuid.UUID) (int64, error)
	CountWorkspaceOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error)
	DeleteAccountGroup(ctx context.Context, arg DeleteAccountGroupParams) (int64, error)
	DeleteAccountSourceRefs(ctx context.Context, arg DeleteAccountSourceRefsParams) error
	DeleteCorporateAction(ctx context.Context, arg DeleteCorporateActionParams) (int64, error)
	DeleteDividendEvent(ctx context.Context, arg DeleteDividendEventParams) error
	DeleteInvestmentPosition(ctx context.Context, arg DeleteInvestmentPositionParams) error
	DeleteInvestmentTrade(ctx context.Context, arg DeleteInvestmentTradeParams) error
	DeleteLotConsumptionsForPosition(ctx context.Context, arg DeleteLotConsumptionsForPositionParams) error
	DeleteLotsForPosition(ctx context.Context, arg DeleteLotsForPositionParams) error
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeleteOtherSessionsByUser(ctx context.Context, arg DeleteOtherSessionsByUserParams) error
	DeletePasskeyForUser(ctx context.Context, arg DeletePasskeyForUserParams) error
	DeleteRecoveryCodesByUser(ctx context.Context, userID uuid.UUID) error
	DeleteSessionByID(ctx context.Context, id string) error
	DeleteSessionByIDReturningUserID(ctx context.Context, id string) (uuid.UUID, error)
	DeleteSessionsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteTOTPCredential(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error)
	DeleteTransactionTag(ctx context.Context, arg DeleteTransactionTagParams) error
	DividendExists(ctx context.Context, arg DividendExistsParams) (bool, error)
	// Lookup an account by exact (name, kind, currency) within a workspace.
	// Used at apply time to merge create_account requests into an account
	// that another file in the same multi-apply batch already created — the
	// preview step ran before any apply committed, so the wizard couldn't
	// see same-batch siblings as candidates and the user's plan defaults to
	// create. Without this divert the second create attempt produces a
	// duplicate account with the same name. Archived rows are included so
	// a re-import resurfaces the prior account instead of cloning around it.
	FindAccountByNameKindCurrency(ctx context.Context, arg FindAccountByNameKindCurrencyParams) (uuid.UUID, error)
	FindBrokerageAccount(ctx context.Context, arg FindBrokerageAccountParams) (FindBrokerageAccountRow, error)
	FindInstrumentByISIN(ctx context.Context, isin *string) (FindInstrumentByISINRow, error)
	FindInstrumentBySymbolAndExchange(ctx context.Context, arg FindInstrumentBySymbolAndExchangeParams) (FindInstrumentBySymbolAndExchangeRow, error)
	FindInstrumentBySymbolOnly(ctx context.Context, symbol string) (FindInstrumentBySymbolOnlyRow, error)
	GetAccountCurrency(ctx context.Context, arg GetAccountCurrencyParams) (string, error)
	GetAccountGroup(ctx context.Context, arg GetAccountGroupParams) (GetAccountGroupRow, error)
	GetAccountKind(ctx context.Context, arg GetAccountKindParams) (string, error)
	// Derived balance rule (spec §5.2):
	//   balance = coalesce(latest_snapshot.balance, opening_balance)
	//           + sum(transactions.amount where status in ('posted','reconciled')
	//                 and booked_at >= snapshot.as_of projected to UTC date)
	//
	// Every account has an "opening" snapshot at create time, so post-opening-day
	// transactions are included correctly.
	GetAccountWithBalance(ctx context.Context, arg GetAccountWithBalanceParams) (GetAccountWithBalanceRow, error)
	GetAuthTokenForConsume(ctx context.Context, arg GetAuthTokenForConsumeParams) (GetAuthTokenForConsumeRow, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetCorporateActionForDelete(ctx context.Context, arg GetCorporateActionForDeleteParams) (GetCorporateActionForDeleteRow, error)
	GetDividendAccountInstrument(ctx context.Context, arg GetDividendAccountInstrumentParams) (GetDividendAccountInstrumentRow, error)
	GetInstrumentByID(ctx context.Context, id uuid.UUID) (GetInstrumentByIDRow, error)
	GetInstrumentBySymbol(ctx context.Context, symbol interface{}) (GetInstrumentBySymbolRow, error)
	GetInstrumentCurrency(ctx context.Context, id uuid.UUID) (string, error)
	GetInvestmentTrade(ctx context.Context, arg GetInvestmentTradeParams) (GetInvestmentTradeRow, error)
	GetInviteForAccept(ctx context.Context, tokenHash []byte) (GetInviteForAcceptRow, error)
	GetInviteForResend(ctx context.Context, arg GetInviteForResendParams) (GetInviteForResendRow, error)
	GetInviteForRevoke(ctx context.Context, arg GetInviteForRevokeParams) (GetInviteForRevokeRow, error)
	GetInvitePreview(ctx context.Context, tokenHash []byte) (GetInvitePreviewRow, error)
	GetMFAChallengeByID(ctx context.Context, id uuid.UUID) (GetMFAChallengeByIDRow, error)
	GetMFAStatus(ctx context.Context, userID uuid.UUID) (GetMFAStatusRow, error)
	GetMembershipRoleForUpdate(ctx context.Context, arg GetMembershipRoleForUpdateParams) (WorkspaceRole, error)
	GetPlatformInviteByTokenHash(ctx context.Context, tokenHash []byte) (PlatformInvite, error)
	GetPlatformInviteForAccept(ctx context.Context, tokenHash []byte) (GetPlatformInviteForAcceptRow, error)
	GetPlatformInviteForRevoke(ctx context.Context, id uuid.UUID) (GetPlatformInviteForRevokeRow, error)
	GetSessionByID(ctx context.Context, id string) (GetSessionByIDRow, error)
	GetTOTPSecretCipher(ctx context.Context, userID uuid.UUID) (string, error)
	GetTOTPSecretCipherAny(ctx context.Context, userID uuid.UUID) (string, error)
	GetTOTPVerifiedAt(ctx context.Context, userID uuid.UUID) (*time.Time, error)
	GetTag(ctx context.Context, arg GetTagParams) (Tag, error)
	GetTradeAccountInstrument(ctx context.Context, arg GetTradeAccountInstrumentParams) (GetTradeAccountInstrumentRow, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error)
	GetUserByEmailWithPassword(ctx context.Context, email string) (GetUserByEmailWithPasswordRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserEmailAndDisplayName(ctx context.Context, id uuid.UUID) (GetUserEmailAndDisplayNameRow, error)
	GetUserEmailAndName(ctx context.Context, id uuid.UUID) (GetUserEmailAndNameRow, error)
	GetUserEmailAndVerification(ctx context.Context, id uuid.UUID) (GetUserEmailAndVerificationRow, error)
	GetUserForPasswordReset(ctx context.Context, arg GetUserForPasswordResetParams) (GetUserForPasswordResetRow, error)
	GetUserIDAndNameByEmail(ctx context.Context, email string) (GetUserIDAndNameByEmailRow, error)
	GetUserIDByEmail(ctx context.Context, email string) (uuid.UUID, error)
	GetUserIsAdmin(ctx context.Context, id uuid.UUID) (bool, error)
	GetUserPasswordHash(ctx context.Context, id uuid.UUID) (string, error)
	GetWorkspaceBaseCurrency(ctx context.Context, id uuid.UUID) (string, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (GetWorkspaceByIDRow, error)
	GetWorkspaceInviteByTokenHash(ctx context.Context, tokenHash []byte) (GetWorkspaceInviteByTokenHashRow, error)
	GetWorkspaceWithMembership(ctx context.Context, arg GetWorkspaceWithMembershipParams) (GetWorkspaceWithMembershipRow, error)
	GetWorkspaceWithOwnership(ctx context.Context, arg GetWorkspaceWithOwnershipParams) (GetWorkspaceWithOwnershipRow, error)
	HasMFAEnrolled(ctx context.Context, userID uuid.UUID) (*bool, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (InsertAccountRow, error)
	InsertAccountGroup(ctx context.Context, arg InsertAccountGroupParams) (InsertAccountGroupRow, error)
	InsertAuditDirect(ctx context.Context, arg InsertAuditDirectParams) error
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertAuditEventWithRequest(ctx context.Context, arg InsertAuditEventWithRequestParams) error
	InsertAuthToken(ctx context.Context, arg InsertAuthTokenParams) error
	InsertBrokerageAccount(ctx context.Context, arg InsertBrokerageAccountParams) error
	InsertBrokerageOpeningSnapshot(ctx context.Context, arg InsertBrokerageOpeningSnapshotParams) error
	InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error)
	InsertCorporateAction(ctx context.Context, arg InsertCorporateActionParams) (InsertCorporateActionRow, error)
	InsertDividendEvent(ctx context.Context, arg InsertDividendEventParams) (InsertDividendEventRow, error)
	InsertDividendEventExec(ctx context.Context, arg InsertDividendEventExecParams) error
	InsertImportAccount(ctx context.Context, arg InsertImportAccountParams) error
	InsertImportBatch(ctx context.Context, arg InsertImportBatchParams) error
	InsertImportTransaction(ctx context.Context, arg InsertImportTransactionParams) error
	InsertInstrument(ctx context.Context, arg InsertInstrumentParams) (InsertInstrumentRow, error)
	InsertInvestmentAccount(ctx context.Context, arg InsertInvestmentAccountParams) error
	InsertInvestmentLot(ctx context.Context, arg InsertInvestmentLotParams) error
	InsertInvestmentTrade(ctx context.Context, arg InsertInvestmentTradeParams) (InsertInvestmentTradeRow, error)
	InsertInvestmentTradeExec(ctx context.Context, arg InsertInvestmentTradeExecParams) error
	InsertInvitedMembership(ctx context.Context, arg InsertInvitedMembershipParams) error
	InsertLoginFailedAudit(ctx context.Context, arg InsertLoginFailedAuditParams) error
	InsertLotConsumption(ctx context.Context, arg InsertLotConsumptionParams) error
	InsertMFAChallenge(ctx context.Context, arg InsertMFAChallengeParams) error
	InsertMembership(ctx context.Context, arg InsertMembershipParams) (InsertMembershipRow, error)
	InsertOpeningSnapshot(ctx context.Context, arg InsertOpeningSnapshotParams) error
	InsertPlatformInvite(ctx context.Context, arg InsertPlatformInviteParams) (PlatformInvite, error)
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertSourceRef(ctx context.Context, arg InsertSourceRefParams) error
	InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error)
	InsertTestUser(ctx context.Context, arg InsertTestUserParams) error
	InsertTestWorkspace(ctx context.Context, arg InsertTestWorkspaceParams) error
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (InsertTransactionRow, error)
	InsertTransactionTag(ctx context.Context, arg InsertTransactionTagParams) error
	InsertUserReturning(ctx context.Context, arg InsertUserReturningParams) (InsertUserReturningRow, error)
	InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) error
	InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (InsertWorkspaceRow, error)
	InsertWorkspaceInvite(ctx context.Context, arg InsertWorkspaceInviteParams) (InsertWorkspaceInviteRow, error)
	InvestmentAccountExists(ctx context.Context, arg InvestmentAccountExistsParams) (bool, error)
	ListAccountGroups(ctx context.Context, workspaceID uuid.UUID) ([]ListAccountGroupsRow, error)
	ListAccountGroupsActive(ctx context.Context, workspaceID uuid.UUID) ([]ListAccountGroupsActiveRow, error)
	ListAccountsWithBalance(ctx context.Context, workspaceID uuid.UUID) ([]ListAccountsWithBalanceRow, error)
	ListAccountsWithBalanceActive(ctx context.Context, workspaceID uuid.UUID) ([]ListAccountsWithBalanceActiveRow, error)
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	ListCorporateActions(ctx context.Context, arg ListCorporateActionsParams) ([]ListCorporateActionsRow, error)
	// Archived accounts are kept in the candidate set so re-importing the
	// same file matches the account the user already imported into instead
	// of silently creating a duplicate. Kind is exposed so the import wizard
	// can avoid auto-suggesting a brokerage import target for a cash group
	// (e.g. Flexible Cash Funds USD interest rows landing in the Conta
	// Pessoal USD checking account because no other USD account exists).
	ListImportAccountMatches(ctx context.Context, workspaceID uuid.UUID) ([]ListImportAccountMatchesRow, error)
	ListInvestmentDividends(ctx context.Context, arg ListInvestmentDividendsParams) ([]ListInvestmentDividendsRow, error)
	ListInvestmentPositions(ctx context.Context, arg ListInvestmentPositionsParams) ([]ListInvestmentPositionsRow, error)
	ListInvestmentTrades(ctx context.Context, arg ListInvestmentTradesParams) ([]ListInvestmentTradesRow, error)
	ListMembersWithUser(ctx context.Context, workspaceID uuid.UUID) ([]ListMembersWithUserRow, error)
	ListOpenPositionInstruments(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenPositionInstrumentsRow, error)
	ListOpenPositionInstrumentsWithPrice(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenPositionInstrumentsWithPriceRow, error)
	ListPasskeysForUser(ctx context.Context, userID uuid.UUID) ([]ListPasskeysForUserRow, error)
	ListPendingInvites(ctx context.Context, workspaceID uuid.UUID) ([]ListPendingInvitesRow, error)
	ListPlatformInvitesActive(ctx context.Context) ([]PlatformInvite, error)
	ListPlatformInvitesAll(ctx context.Context, arg ListPlatformInvitesAllParams) ([]PlatformInvite, error)
	ListPositionAccountsForInstrument(ctx context.Context, arg ListPositionAccountsForInstrumentParams) ([]uuid.UUID, error)
	ListTouchedInvestmentPairs(ctx context.Context, workspaceID uuid.UUID) ([]ListTouchedInvestmentPairsRow, error)
	ListUnconsumedRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]ListUnconsumedRecoveryCodesRow, error)
	ListWebAuthnCredentials(ctx context.Context, userID uuid.UUID) ([]ListWebAuthnCredentialsRow, error)
	// Surface every (provider, external_id) tuple already present in the
	// workspace so classify can dedup re-imports across accounts. The
	// source_refs unique index is workspace-scoped, but the per-account
	// existing-row check used at classify time misses rows attached to a
	// different account (e.g. an earlier import that targeted a different
	// account, or a rerun that picked "create_account" instead of merging
	// into the prior target). Without this lookup the apply would attempt
	// to insert a duplicate source_ref and the whole file would 23505 out.
	ListWorkspaceExternalIDs(ctx context.Context, arg ListWorkspaceExternalIDsParams) ([]string, error)
	ListWorkspacesWithRoleByUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesWithRoleByUserRow, error)
	LoadCorporateActionEvents(ctx context.Context, arg LoadCorporateActionEventsParams) ([]LoadCorporateActionEventsRow, error)
	LoadDividendEvents(ctx context.Context, arg LoadDividendEventsParams) ([]LoadDividendEventsRow, error)
	LoadEnabledRules(ctx context.Context, workspaceID uuid.UUID) ([]CategorizationRule, error)
	// Load existing transactions in the date range for duplicate/conflict detection.
	LoadExistingTransactions(ctx context.Context, arg LoadExistingTransactionsParams) ([]LoadExistingTransactionsRow, error)
	// Find consolidated-MMF "net interest" rows in this account that fall
	// within a date range, so a higher-fidelity savings-statement import can
	// void them. The granular savings-statement export breaks the same daily
	// interest into separate Interest PAID + Service Fee rows; without this
	// voiding step a user importing both files double-counts the interest.
	LoadMMFSummaryCandidates(ctx context.Context, arg LoadMMFSummaryCandidatesParams) ([]LoadMMFSummaryCandidatesRow, error)
	// Load real (non-synthetic) rows near a synthetic for residual-explained check.
	// Only considers rows from a different import batch than the synthetic itself.
	LoadRealRowsForSynthetic(ctx context.Context, arg LoadRealRowsForSyntheticParams) ([]LoadRealRowsForSyntheticRow, error)
	// Scan synthetic balance-reconcile rows for potential retirement.
	// gap_start_date is the consolidated row date that established the previous
	// balance for this synthetic; together with booked_at it bounds the interval
	// where the missing real transaction must have occurred. Older synthetics
	// (pre-#TBD) didn't store this and fall back to NULL.
	LoadSyntheticCandidates(ctx context.Context, arg LoadSyntheticCandidatesParams) ([]LoadSyntheticCandidatesRow, error)
	LoadTradeEvents(ctx context.Context, arg LoadTradeEventsParams) ([]LoadTradeEventsRow, error)
	LoadTransactionSnapshot(ctx context.Context, arg LoadTransactionSnapshotParams) (LoadTransactionSnapshotRow, error)
	LookupCachedFXRate(ctx context.Context, arg LookupCachedFXRateParams) (pgtype.Numeric, error)
	LookupCachedLatestPrice(ctx context.Context, instrumentID uuid.UUID) (LookupCachedLatestPriceRow, error)
	LookupCachedPriceRange(ctx context.Context, arg LookupCachedPriceRangeParams) ([]LookupCachedPriceRangeRow, error)
	MarkInviteAccepted(ctx context.Context, id uuid.UUID) error
	MarkInviteRevoked(ctx context.Context, id uuid.UUID) error
	MarkPlatformInviteAccepted(ctx context.Context, arg MarkPlatformInviteAcceptedParams) error
	MarkPlatformInviteRevoked(ctx context.Context, arg MarkPlatformInviteRevokedParams) error
	PersistFXRate(ctx context.Context, arg PersistFXRateParams) error
	PersistInstrumentPrice(ctx context.Context, arg PersistInstrumentPriceParams) error
	ReorderAccount(ctx context.Context, arg ReorderAccountParams) (int64, error)
	ReorderAccountGroup(ctx context.Context, arg ReorderAccountGroupParams) (int64, error)
	RestoreWorkspace(ctx context.Context, id uuid.UUID) (int64, error)
	RotateWorkspaceInviteToken(ctx context.Context, arg RotateWorkspaceInviteTokenParams) (RotateWorkspaceInviteTokenRow, error)
	SearchInstruments(ctx context.Context, arg SearchInstrumentsParams) ([]SearchInstrumentsRow, error)
	SoftDeleteWorkspace(ctx context.Context, id uuid.UUID) (int64, error)
	StampRuleLastMatchedAt(ctx context.Context, arg StampRuleLastMatchedAtParams) error
	SweepDeletedWorkspaces(ctx context.Context, gracePeriodSeconds float64) ([]string, error)
	TagExists(ctx context.Context, arg TagExistsParams) (bool, error)
	TradeExists(ctx context.Context, arg TradeExistsParams) (bool, error)
	TransactionExists(ctx context.Context, arg TransactionExistsParams) (bool, error)
	// Opt-in reactivate: clear archived_at when the user explicitly
	// asked to resurface this account. No-op for non-archived rows.
	UnarchiveAccount(ctx context.Context, arg UnarchiveAccountParams) error
	UpdateMFAChallengeWebAuthnState(ctx context.Context, arg UpdateMFAChallengeWebAuthnStateParams) error
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error
	UpdateSessionLastSeen(ctx context.Context, arg UpdateSessionLastSeenParams) error
	UpdateSessionReauthAt(ctx context.Context, arg UpdateSessionReauthAtParams) error
	UpdateSessionReauthByID(ctx context.Context, arg UpdateSessionReauthByIDParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserLastLoginAt(ctx context.Context, arg UpdateUserLastLoginAtParams) error
	UpdateUserLastWorkspace(ctx context.Context, arg UpdateUserLastWorkspaceParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWebAuthnSignCount(ctx context.Context, arg UpdateWebAuthnSignCountParams) error
	UpsertInvestmentPosition(ctx context.Context, arg UpsertInvestmentPositionParams) error
	UpsertMembershipOnInvite(ctx context.Context, arg UpsertMembershipOnInviteParams) error
	UpsertTOTPCredential(ctx context.Context, arg UpsertTOTPCredentialParams) (int64, error)
	UserExists(ctx context.Context) (bool, error)
	VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) (int64, error)
	VoidTransaction(ctx context.Context, arg VoidTransactionParams) error
}

var _ Querier = (*Queries)(nil)
