// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUserIDByEmail(ctx context.Context, email string) (uuid.UUID, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertAuditEventWithRequest(ctx context.Context, arg InsertAuditEventWithRequestParams) error
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
}

var _ Querier = (*Queries)(nil)
