// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :exec
UPDATE auth_recovery_codes SET consumed_at = $2 WHERE id = $1
`

type ConsumeRecoveryCodeParams struct {
	ID         uuid.UUID  `json:"id"`
	ConsumedAt *time.Time `json:"consumed_at"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, consumeRecoveryCode, arg.ID, arg.ConsumedAt)
	return err
}

const countUnconsumedRecoveryCodes = `-- name: CountUnconsumedRecoveryCodes :one
SELECT count(*) FROM auth_recovery_codes
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) CountUnconsumedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnconsumedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecoveryCodesByUser = `-- name: DeleteRecoveryCodesByUser :exec
DELETE FROM auth_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodesByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesByUser, userID)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO auth_recovery_codes (id, user_id, code_hash, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertRecoveryCodeParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CodeHash  string    `json:"code_hash"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.CreatedAt,
	)
	return err
}

const listUnconsumedRecoveryCodes = `-- name: ListUnconsumedRecoveryCodes :many
SELECT id, code_hash FROM auth_recovery_codes
WHERE user_id = $1 AND consumed_at IS NULL
FOR UPDATE
`

type ListUnconsumedRecoveryCodesRow struct {
	ID       uuid.UUID `json:"id"`
	CodeHash string    `json:"code_hash"`
}

func (q *Queries) ListUnconsumedRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]ListUnconsumedRecoveryCodesRow, error) {
	rows, err := q.db.Query(ctx, listUnconsumedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnconsumedRecoveryCodesRow{}
	for rows.Next() {
		var i ListUnconsumedRecoveryCodesRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
