// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules_apply.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const loadEnabledRules = `-- name: LoadEnabledRules :many
SELECT id, workspace_id, priority, when_jsonb, then_jsonb, enabled,
       last_matched_at, created_at, updated_at
FROM categorization_rules
WHERE workspace_id = $1 AND enabled = true
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) LoadEnabledRules(ctx context.Context, workspaceID uuid.UUID) ([]CategorizationRule, error) {
	rows, err := q.db.Query(ctx, loadEnabledRules, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategorizationRule{}
	for rows.Next() {
		var i CategorizationRule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Priority,
			&i.WhenJsonb,
			&i.ThenJsonb,
			&i.Enabled,
			&i.LastMatchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadTransactionSnapshot = `-- name: LoadTransactionSnapshot :one
SELECT id, workspace_id, account_id, amount::text AS amount,
       counterparty_raw, description, merchant_id, category_id, count_as_expense
FROM transactions
WHERE workspace_id = $1 AND id = $2
`

type LoadTransactionSnapshotParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

type LoadTransactionSnapshotRow struct {
	ID              uuid.UUID  `json:"id"`
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	AccountID       uuid.UUID  `json:"account_id"`
	Amount          string     `json:"amount"`
	CounterpartyRaw *string    `json:"counterparty_raw"`
	Description     *string    `json:"description"`
	MerchantID      *uuid.UUID `json:"merchant_id"`
	CategoryID      *uuid.UUID `json:"category_id"`
	CountAsExpense  *bool      `json:"count_as_expense"`
}

func (q *Queries) LoadTransactionSnapshot(ctx context.Context, arg LoadTransactionSnapshotParams) (LoadTransactionSnapshotRow, error) {
	row := q.db.QueryRow(ctx, loadTransactionSnapshot, arg.WorkspaceID, arg.ID)
	var i LoadTransactionSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Amount,
		&i.CounterpartyRaw,
		&i.Description,
		&i.MerchantID,
		&i.CategoryID,
		&i.CountAsExpense,
	)
	return i, err
}

const stampRuleLastMatchedAt = `-- name: StampRuleLastMatchedAt :exec
UPDATE categorization_rules SET last_matched_at = now()
WHERE workspace_id = $1 AND id = $2
`

type StampRuleLastMatchedAtParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) StampRuleLastMatchedAt(ctx context.Context, arg StampRuleLastMatchedAtParams) error {
	_, err := q.db.Exec(ctx, stampRuleLastMatchedAt, arg.WorkspaceID, arg.ID)
	return err
}
