// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbq

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const deleteOtherSessionsByUser = `-- name: DeleteOtherSessionsByUser :exec
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteOtherSessionsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     string    `json:"id"`
}

func (q *Queries) DeleteOtherSessionsByUser(ctx context.Context, arg DeleteOtherSessionsByUserParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessionsByUser, arg.UserID, arg.ID)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const deleteSessionByIDReturningUserID = `-- name: DeleteSessionByIDReturningUserID :one
DELETE FROM sessions WHERE id = $1 RETURNING user_id
`

func (q *Queries) DeleteSessionByIDReturningUserID(ctx context.Context, id string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteSessionByIDReturningUserID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, created_at, expires_at, last_seen_at, reauth_at
FROM sessions WHERE id = $1
`

type GetSessionByIDRow struct {
	ID         string     `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	LastSeenAt time.Time  `json:"last_seen_at"`
	ReauthAt   *time.Time `json:"reauth_at"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id string) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.ReauthAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, created_at, expires_at, last_seen_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $3, $5, $6)
`

type InsertSessionParams struct {
	ID        string      `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	CreatedAt time.Time   `json:"created_at"`
	ExpiresAt time.Time   `json:"expires_at"`
	UserAgent *string     `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE sessions SET last_seen_at = $1 WHERE id = $2
`

type UpdateSessionLastSeenParams struct {
	LastSeenAt time.Time `json:"last_seen_at"`
	ID         string    `json:"id"`
}

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, arg UpdateSessionLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, arg.LastSeenAt, arg.ID)
	return err
}

const updateSessionReauthAt = `-- name: UpdateSessionReauthAt :exec
UPDATE sessions SET reauth_at = $3 WHERE id = $1 AND user_id = $2
`

type UpdateSessionReauthAtParams struct {
	ID       string     `json:"id"`
	UserID   uuid.UUID  `json:"user_id"`
	ReauthAt *time.Time `json:"reauth_at"`
}

func (q *Queries) UpdateSessionReauthAt(ctx context.Context, arg UpdateSessionReauthAtParams) error {
	_, err := q.db.Exec(ctx, updateSessionReauthAt, arg.ID, arg.UserID, arg.ReauthAt)
	return err
}
