// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveTag = `-- name: ArchiveTag :execrows
UPDATE tags
SET archived_at = coalesce(archived_at, $1)
WHERE workspace_id = $2 AND id = $3
`

type ArchiveTagParams struct {
	Now         *time.Time `json:"now"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ID          uuid.UUID  `json:"id"`
}

func (q *Queries) ArchiveTag(ctx context.Context, arg ArchiveTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveTag, arg.Now, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTag = `-- name: GetTag :one
SELECT id, workspace_id, name, color, archived_at, created_at, updated_at
FROM tags
WHERE workspace_id = $1 AND id = $2
`

type GetTagParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, arg.WorkspaceID, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (id, workspace_id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, color, archived_at, created_at, updated_at
`

type InsertTagParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Color       *string   `json:"color"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tagExists = `-- name: TagExists :one
SELECT true AS ok FROM tags WHERE workspace_id = $1 AND id = $2
`

type TagExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) TagExists(ctx context.Context, arg TagExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tagExists, arg.WorkspaceID, arg.ID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}
