// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: totp.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpTOTPLastUsedStep = `-- name: BumpTOTPLastUsedStep :execrows
UPDATE totp_credentials
SET last_used_step = $2
WHERE user_id = $1 AND (last_used_step IS NULL OR last_used_step < $2)
`

type BumpTOTPLastUsedStepParams struct {
	UserID       uuid.UUID `json:"user_id"`
	LastUsedStep *int64    `json:"last_used_step"`
}

func (q *Queries) BumpTOTPLastUsedStep(ctx context.Context, arg BumpTOTPLastUsedStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpTOTPLastUsedStep, arg.UserID, arg.LastUsedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmTOTPCredential = `-- name: ConfirmTOTPCredential :exec
UPDATE totp_credentials SET verified_at = $2 WHERE user_id = $1
`

type ConfirmTOTPCredentialParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	VerifiedAt *time.Time `json:"verified_at"`
}

func (q *Queries) ConfirmTOTPCredential(ctx context.Context, arg ConfirmTOTPCredentialParams) error {
	_, err := q.db.Exec(ctx, confirmTOTPCredential, arg.UserID, arg.VerifiedAt)
	return err
}

const deleteTOTPCredential = `-- name: DeleteTOTPCredential :execrows
DELETE FROM totp_credentials WHERE user_id = $1
`

func (q *Queries) DeleteTOTPCredential(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTOTPCredential, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTOTPSecretCipher = `-- name: GetTOTPSecretCipher :one
SELECT secret_cipher FROM totp_credentials WHERE user_id = $1 AND verified_at IS NOT NULL
`

func (q *Queries) GetTOTPSecretCipher(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTOTPSecretCipher, userID)
	var secret_cipher string
	err := row.Scan(&secret_cipher)
	return secret_cipher, err
}

const getTOTPSecretCipherAny = `-- name: GetTOTPSecretCipherAny :one
SELECT secret_cipher FROM totp_credentials WHERE user_id = $1
`

func (q *Queries) GetTOTPSecretCipherAny(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTOTPSecretCipherAny, userID)
	var secret_cipher string
	err := row.Scan(&secret_cipher)
	return secret_cipher, err
}

const getTOTPVerifiedAt = `-- name: GetTOTPVerifiedAt :one
SELECT verified_at FROM totp_credentials WHERE user_id = $1
`

func (q *Queries) GetTOTPVerifiedAt(ctx context.Context, userID uuid.UUID) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getTOTPVerifiedAt, userID)
	var verified_at *time.Time
	err := row.Scan(&verified_at)
	return verified_at, err
}

const upsertTOTPCredential = `-- name: UpsertTOTPCredential :execrows
INSERT INTO totp_credentials (id, user_id, secret_cipher, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET secret_cipher = excluded.secret_cipher, created_at = excluded.created_at, verified_at = null
WHERE totp_credentials.verified_at IS NULL
`

type UpsertTOTPCredentialParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	SecretCipher string    `json:"secret_cipher"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) UpsertTOTPCredential(ctx context.Context, arg UpsertTOTPCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertTOTPCredential,
		arg.ID,
		arg.UserID,
		arg.SecretCipher,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
