// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_tags.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const deleteTransactionTag = `-- name: DeleteTransactionTag :exec
DELETE FROM transaction_tags
WHERE workspace_id = $1 AND transaction_id = $2 AND tag_id = $3
`

type DeleteTransactionTagParams struct {
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	TagID         uuid.UUID `json:"tag_id"`
}

func (q *Queries) DeleteTransactionTag(ctx context.Context, arg DeleteTransactionTagParams) error {
	_, err := q.db.Exec(ctx, deleteTransactionTag, arg.WorkspaceID, arg.TransactionID, arg.TagID)
	return err
}

const insertTransactionTag = `-- name: InsertTransactionTag :exec
INSERT INTO transaction_tags (transaction_id, tag_id, workspace_id)
VALUES ($1, $2, $3)
ON CONFLICT (transaction_id, tag_id) DO NOTHING
`

type InsertTransactionTagParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	TagID         uuid.UUID `json:"tag_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
}

func (q *Queries) InsertTransactionTag(ctx context.Context, arg InsertTransactionTagParams) error {
	_, err := q.db.Exec(ctx, insertTransactionTag, arg.TransactionID, arg.TagID, arg.WorkspaceID)
	return err
}

const transactionExists = `-- name: TransactionExists :one
SELECT true AS ok FROM transactions WHERE workspace_id = $1 AND id = $2
`

type TransactionExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) TransactionExists(ctx context.Context, arg TransactionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, transactionExists, arg.WorkspaceID, arg.ID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}
