// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE workspace_id = $1 AND id = $2
`

type DeleteTransactionParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, workspace_id, account_id, status::text, booked_at, value_at, posted_at,
       amount::text, currency, original_amount::text, original_currency::text,
       merchant_id, category_id, counterparty_raw, description, notes,
       count_as_expense, created_at, updated_at
FROM transactions
WHERE workspace_id = $1 AND id = $2
`

type GetTransactionParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

type GetTransactionRow struct {
	ID               uuid.UUID  `json:"id"`
	WorkspaceID      uuid.UUID  `json:"workspace_id"`
	AccountID        uuid.UUID  `json:"account_id"`
	Status           string     `json:"status"`
	BookedAt         time.Time  `json:"booked_at"`
	ValueAt          *time.Time `json:"value_at"`
	PostedAt         *time.Time `json:"posted_at"`
	Amount           string     `json:"amount"`
	Currency         string     `json:"currency"`
	OriginalAmount   string     `json:"original_amount"`
	OriginalCurrency string     `json:"original_currency"`
	MerchantID       *uuid.UUID `json:"merchant_id"`
	CategoryID       *uuid.UUID `json:"category_id"`
	CounterpartyRaw  *string    `json:"counterparty_raw"`
	Description      *string    `json:"description"`
	Notes            *string    `json:"notes"`
	CountAsExpense   *bool      `json:"count_as_expense"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.WorkspaceID, arg.ID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Status,
		&i.BookedAt,
		&i.ValueAt,
		&i.PostedAt,
		&i.Amount,
		&i.Currency,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.MerchantID,
		&i.CategoryID,
		&i.CounterpartyRaw,
		&i.Description,
		&i.Notes,
		&i.CountAsExpense,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
  id, workspace_id, account_id, status, booked_at, value_at, posted_at,
  amount, currency, merchant_id, category_id,
  counterparty_raw, description, notes, count_as_expense
) VALUES (
  $1, $2, $3, $4::transaction_status, $5, $6, $7,
  $8::numeric, $9, $10, $11,
  $12, $13, $14, $15
)
RETURNING id, workspace_id, account_id, status::text, booked_at, value_at, posted_at,
          amount::text, currency, original_amount::text, original_currency::text,
          merchant_id, category_id, counterparty_raw, description, notes,
          count_as_expense, created_at, updated_at
`

type InsertTransactionParams struct {
	ID              uuid.UUID         `json:"id"`
	WorkspaceID     uuid.UUID         `json:"workspace_id"`
	AccountID       uuid.UUID         `json:"account_id"`
	Status          TransactionStatus `json:"status"`
	BookedAt        time.Time         `json:"booked_at"`
	ValueAt         *time.Time        `json:"value_at"`
	PostedAt        *time.Time        `json:"posted_at"`
	Amount          pgtype.Numeric    `json:"amount"`
	Currency        string            `json:"currency"`
	MerchantID      *uuid.UUID        `json:"merchant_id"`
	CategoryID      *uuid.UUID        `json:"category_id"`
	CounterpartyRaw *string           `json:"counterparty_raw"`
	Description     *string           `json:"description"`
	Notes           *string           `json:"notes"`
	CountAsExpense  *bool             `json:"count_as_expense"`
}

type InsertTransactionRow struct {
	ID               uuid.UUID  `json:"id"`
	WorkspaceID      uuid.UUID  `json:"workspace_id"`
	AccountID        uuid.UUID  `json:"account_id"`
	Status           string     `json:"status"`
	BookedAt         time.Time  `json:"booked_at"`
	ValueAt          *time.Time `json:"value_at"`
	PostedAt         *time.Time `json:"posted_at"`
	Amount           string     `json:"amount"`
	Currency         string     `json:"currency"`
	OriginalAmount   string     `json:"original_amount"`
	OriginalCurrency string     `json:"original_currency"`
	MerchantID       *uuid.UUID `json:"merchant_id"`
	CategoryID       *uuid.UUID `json:"category_id"`
	CounterpartyRaw  *string    `json:"counterparty_raw"`
	Description      *string    `json:"description"`
	Notes            *string    `json:"notes"`
	CountAsExpense   *bool      `json:"count_as_expense"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (InsertTransactionRow, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.ID,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Status,
		arg.BookedAt,
		arg.ValueAt,
		arg.PostedAt,
		arg.Amount,
		arg.Currency,
		arg.MerchantID,
		arg.CategoryID,
		arg.CounterpartyRaw,
		arg.Description,
		arg.Notes,
		arg.CountAsExpense,
	)
	var i InsertTransactionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Status,
		&i.BookedAt,
		&i.ValueAt,
		&i.PostedAt,
		&i.Amount,
		&i.Currency,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.MerchantID,
		&i.CategoryID,
		&i.CounterpartyRaw,
		&i.Description,
		&i.Notes,
		&i.CountAsExpense,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
