// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :exec
INSERT INTO webauthn_credentials (id, user_id, credential_id, public_key, sign_count, transports, label, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertWebAuthnCredentialParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	CredentialID []byte    `json:"credential_id"`
	PublicKey    []byte    `json:"public_key"`
	SignCount    int64     `json:"sign_count"`
	Transports   []string  `json:"transports"`
	Label        *string   `json:"label"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, insertWebAuthnCredential,
		arg.ID,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Label,
		arg.CreatedAt,
	)
	return err
}

const listWebAuthnCredentials = `-- name: ListWebAuthnCredentials :many
SELECT credential_id, public_key, sign_count, coalesce(transports, '{}') AS transports
FROM webauthn_credentials WHERE user_id = $1
`

type ListWebAuthnCredentialsRow struct {
	CredentialID []byte   `json:"credential_id"`
	PublicKey    []byte   `json:"public_key"`
	SignCount    int64    `json:"sign_count"`
	Transports   []string `json:"transports"`
}

func (q *Queries) ListWebAuthnCredentials(ctx context.Context, userID uuid.UUID) ([]ListWebAuthnCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebAuthnCredentialsRow{}
	for rows.Next() {
		var i ListWebAuthnCredentialsRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebAuthnSignCount = `-- name: UpdateWebAuthnSignCount :exec
UPDATE webauthn_credentials SET sign_count = $2
WHERE user_id = $1 AND credential_id = $3
`

type UpdateWebAuthnSignCountParams struct {
	UserID       uuid.UUID `json:"user_id"`
	SignCount    int64     `json:"sign_count"`
	CredentialID []byte    `json:"credential_id"`
}

func (q *Queries) UpdateWebAuthnSignCount(ctx context.Context, arg UpdateWebAuthnSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnSignCount, arg.UserID, arg.SignCount, arg.CredentialID)
	return err
}
