// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, base_currency, cycle_anchor_day, locale, timezone,
       deleted_at, created_at
FROM workspaces
WHERE id = $1 AND deleted_at IS NULL
`

type GetWorkspaceByIDRow struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	BaseCurrency   string     `json:"base_currency"`
	CycleAnchorDay int16      `json:"cycle_anchor_day"`
	Locale         string     `json:"locale"`
	Timezone       string     `json:"timezone"`
	DeletedAt      *time.Time `json:"deleted_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (GetWorkspaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i GetWorkspaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BaseCurrency,
		&i.CycleAnchorDay,
		&i.Locale,
		&i.Timezone,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkspace = `-- name: InsertWorkspace :one
INSERT INTO workspaces (id, name, slug, base_currency, cycle_anchor_day, locale, timezone)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, slug, base_currency, cycle_anchor_day, locale, timezone, deleted_at, created_at
`

type InsertWorkspaceParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	BaseCurrency   string    `json:"base_currency"`
	CycleAnchorDay int16     `json:"cycle_anchor_day"`
	Locale         string    `json:"locale"`
	Timezone       string    `json:"timezone"`
}

type InsertWorkspaceRow struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	BaseCurrency   string     `json:"base_currency"`
	CycleAnchorDay int16      `json:"cycle_anchor_day"`
	Locale         string     `json:"locale"`
	Timezone       string     `json:"timezone"`
	DeletedAt      *time.Time `json:"deleted_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (InsertWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, insertWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.BaseCurrency,
		arg.CycleAnchorDay,
		arg.Locale,
		arg.Timezone,
	)
	var i InsertWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BaseCurrency,
		&i.CycleAnchorDay,
		&i.Locale,
		&i.Timezone,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspacesWithRoleByUser = `-- name: ListWorkspacesWithRoleByUser :many
SELECT t.id, t.name, t.slug, t.base_currency, t.cycle_anchor_day,
       t.locale, t.timezone, t.deleted_at, t.created_at, m.role
FROM workspace_memberships m
JOIN workspaces t ON t.id = m.workspace_id
WHERE m.user_id = $1 AND t.deleted_at IS NULL
ORDER BY t.name
`

type ListWorkspacesWithRoleByUserRow struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	Slug           string        `json:"slug"`
	BaseCurrency   string        `json:"base_currency"`
	CycleAnchorDay int16         `json:"cycle_anchor_day"`
	Locale         string        `json:"locale"`
	Timezone       string        `json:"timezone"`
	DeletedAt      *time.Time    `json:"deleted_at"`
	CreatedAt      time.Time     `json:"created_at"`
	Role           WorkspaceRole `json:"role"`
}

func (q *Queries) ListWorkspacesWithRoleByUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesWithRoleByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesWithRoleByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesWithRoleByUserRow{}
	for rows.Next() {
		var i ListWorkspacesWithRoleByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.BaseCurrency,
			&i.CycleAnchorDay,
			&i.Locale,
			&i.Timezone,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreWorkspace = `-- name: RestoreWorkspace :execrows
UPDATE workspaces SET deleted_at = NULL WHERE id = $1
`

func (q *Queries) RestoreWorkspace(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :execrows
UPDATE workspaces SET deleted_at = coalesce(deleted_at, now()) WHERE id = $1
`

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
