// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_memberships.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getWorkspaceWithMembership = `-- name: GetWorkspaceWithMembership :one
SELECT t.id, t.name, t.slug, t.base_currency, t.cycle_anchor_day,
       t.locale, t.timezone, t.deleted_at, t.created_at, m.role
FROM workspaces t
JOIN workspace_memberships m ON m.workspace_id = t.id
WHERE t.id = $1 AND m.user_id = $2 AND t.deleted_at IS NULL
`

type GetWorkspaceWithMembershipParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetWorkspaceWithMembershipRow struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	Slug           string        `json:"slug"`
	BaseCurrency   string        `json:"base_currency"`
	CycleAnchorDay int16         `json:"cycle_anchor_day"`
	Locale         string        `json:"locale"`
	Timezone       string        `json:"timezone"`
	DeletedAt      *time.Time    `json:"deleted_at"`
	CreatedAt      time.Time     `json:"created_at"`
	Role           WorkspaceRole `json:"role"`
}

func (q *Queries) GetWorkspaceWithMembership(ctx context.Context, arg GetWorkspaceWithMembershipParams) (GetWorkspaceWithMembershipRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceWithMembership, arg.ID, arg.UserID)
	var i GetWorkspaceWithMembershipRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BaseCurrency,
		&i.CycleAnchorDay,
		&i.Locale,
		&i.Timezone,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getWorkspaceWithOwnership = `-- name: GetWorkspaceWithOwnership :one
SELECT t.id, t.name, t.slug, t.base_currency, t.cycle_anchor_day,
       t.locale, t.timezone, t.deleted_at, t.created_at, m.role
FROM workspaces t
JOIN workspace_memberships m ON m.workspace_id = t.id
WHERE t.id = $1 AND m.user_id = $2 AND m.role = 'owner'
`

type GetWorkspaceWithOwnershipParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetWorkspaceWithOwnershipRow struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	Slug           string        `json:"slug"`
	BaseCurrency   string        `json:"base_currency"`
	CycleAnchorDay int16         `json:"cycle_anchor_day"`
	Locale         string        `json:"locale"`
	Timezone       string        `json:"timezone"`
	DeletedAt      *time.Time    `json:"deleted_at"`
	CreatedAt      time.Time     `json:"created_at"`
	Role           WorkspaceRole `json:"role"`
}

func (q *Queries) GetWorkspaceWithOwnership(ctx context.Context, arg GetWorkspaceWithOwnershipParams) (GetWorkspaceWithOwnershipRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceWithOwnership, arg.ID, arg.UserID)
	var i GetWorkspaceWithOwnershipRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BaseCurrency,
		&i.CycleAnchorDay,
		&i.Locale,
		&i.Timezone,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}
