// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_invites.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkIsWorkspaceOwner = `-- name: CheckIsWorkspaceOwner :one
SELECT exists(
    SELECT 1 FROM workspace_memberships
    WHERE workspace_id = $1 AND user_id = $2 AND role = 'owner'
) AS is_owner
`

type CheckIsWorkspaceOwnerParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckIsWorkspaceOwner(ctx context.Context, arg CheckIsWorkspaceOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIsWorkspaceOwner, arg.WorkspaceID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const getInviteForAccept = `-- name: GetInviteForAccept :one
SELECT id, workspace_id, email, role::text AS role, expires_at, revoked_at, accepted_at
FROM workspace_invites
WHERE token_hash = $1
FOR UPDATE
`

type GetInviteForAcceptRow struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Email       string     `json:"email"`
	Role        string     `json:"role"`
	ExpiresAt   time.Time  `json:"expires_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
	AcceptedAt  *time.Time `json:"accepted_at"`
}

func (q *Queries) GetInviteForAccept(ctx context.Context, tokenHash []byte) (GetInviteForAcceptRow, error) {
	row := q.db.QueryRow(ctx, getInviteForAccept, tokenHash)
	var i GetInviteForAcceptRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getInviteForRevoke = `-- name: GetInviteForRevoke :one
SELECT invited_by_user_id, revoked_at, accepted_at
FROM workspace_invites
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type GetInviteForRevokeParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetInviteForRevokeRow struct {
	InvitedByUserID uuid.UUID  `json:"invited_by_user_id"`
	RevokedAt       *time.Time `json:"revoked_at"`
	AcceptedAt      *time.Time `json:"accepted_at"`
}

func (q *Queries) GetInviteForRevoke(ctx context.Context, arg GetInviteForRevokeParams) (GetInviteForRevokeRow, error) {
	row := q.db.QueryRow(ctx, getInviteForRevoke, arg.ID, arg.WorkspaceID)
	var i GetInviteForRevokeRow
	err := row.Scan(&i.InvitedByUserID, &i.RevokedAt, &i.AcceptedAt)
	return i, err
}

const getInvitePreview = `-- name: GetInvitePreview :one
SELECT i.workspace_id, t.name AS workspace_name, t.slug AS workspace_slug,
       u.display_name AS inviter_display_name,
       i.email, i.role::text AS role, i.expires_at, i.revoked_at, i.accepted_at
FROM workspace_invites i
JOIN workspaces t ON t.id = i.workspace_id
JOIN users u ON u.id = i.invited_by_user_id
WHERE i.token_hash = $1 AND t.deleted_at IS NULL
`

type GetInvitePreviewRow struct {
	WorkspaceID        uuid.UUID  `json:"workspace_id"`
	WorkspaceName      string     `json:"workspace_name"`
	WorkspaceSlug      string     `json:"workspace_slug"`
	InviterDisplayName string     `json:"inviter_display_name"`
	Email              string     `json:"email"`
	Role               string     `json:"role"`
	ExpiresAt          time.Time  `json:"expires_at"`
	RevokedAt          *time.Time `json:"revoked_at"`
	AcceptedAt         *time.Time `json:"accepted_at"`
}

func (q *Queries) GetInvitePreview(ctx context.Context, tokenHash []byte) (GetInvitePreviewRow, error) {
	row := q.db.QueryRow(ctx, getInvitePreview, tokenHash)
	var i GetInvitePreviewRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.WorkspaceSlug,
		&i.InviterDisplayName,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getUserEmailAndVerification = `-- name: GetUserEmailAndVerification :one
SELECT email, email_verified_at FROM users WHERE id = $1
`

type GetUserEmailAndVerificationRow struct {
	Email           string     `json:"email"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
}

func (q *Queries) GetUserEmailAndVerification(ctx context.Context, id uuid.UUID) (GetUserEmailAndVerificationRow, error) {
	row := q.db.QueryRow(ctx, getUserEmailAndVerification, id)
	var i GetUserEmailAndVerificationRow
	err := row.Scan(&i.Email, &i.EmailVerifiedAt)
	return i, err
}

const insertWorkspaceInvite = `-- name: InsertWorkspaceInvite :one
INSERT INTO workspace_invites (id, workspace_id, email, role, token_hash,
                               invited_by_user_id, expires_at)
VALUES ($1, $2, $3, $4::workspace_role, $5, $6, $7)
RETURNING id, workspace_id, email, role::text AS role, invited_by_user_id,
          created_at, expires_at
`

type InsertWorkspaceInviteParams struct {
	ID              uuid.UUID     `json:"id"`
	WorkspaceID     uuid.UUID     `json:"workspace_id"`
	Email           string        `json:"email"`
	Column4         WorkspaceRole `json:"column_4"`
	TokenHash       []byte        `json:"token_hash"`
	InvitedByUserID uuid.UUID     `json:"invited_by_user_id"`
	ExpiresAt       time.Time     `json:"expires_at"`
}

type InsertWorkspaceInviteRow struct {
	ID              uuid.UUID `json:"id"`
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	Email           string    `json:"email"`
	Role            string    `json:"role"`
	InvitedByUserID uuid.UUID `json:"invited_by_user_id"`
	CreatedAt       time.Time `json:"created_at"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) InsertWorkspaceInvite(ctx context.Context, arg InsertWorkspaceInviteParams) (InsertWorkspaceInviteRow, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.Column4,
		arg.TokenHash,
		arg.InvitedByUserID,
		arg.ExpiresAt,
	)
	var i InsertWorkspaceInviteRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT id, email, role::text AS role, invited_by_user_id, created_at, expires_at
FROM workspace_invites
WHERE workspace_id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

type ListPendingInvitesRow struct {
	ID              uuid.UUID `json:"id"`
	Email           string    `json:"email"`
	Role            string    `json:"role"`
	InvitedByUserID uuid.UUID `json:"invited_by_user_id"`
	CreatedAt       time.Time `json:"created_at"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) ListPendingInvites(ctx context.Context, workspaceID uuid.UUID) ([]ListPendingInvitesRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitesRow{}
	for rows.Next() {
		var i ListPendingInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.InvitedByUserID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE workspace_invites SET accepted_at = now() WHERE id = $1
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}

const markInviteRevoked = `-- name: MarkInviteRevoked :exec
UPDATE workspace_invites SET revoked_at = now() WHERE id = $1
`

func (q *Queries) MarkInviteRevoked(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInviteRevoked, id)
	return err
}

const upsertMembershipOnInvite = `-- name: UpsertMembershipOnInvite :exec
INSERT INTO workspace_memberships (workspace_id, user_id, role)
VALUES ($1, $2, $3::workspace_role)
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type UpsertMembershipOnInviteParams struct {
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	UserID      uuid.UUID     `json:"user_id"`
	Column3     WorkspaceRole `json:"column_3"`
}

func (q *Queries) UpsertMembershipOnInvite(ctx context.Context, arg UpsertMembershipOnInviteParams) error {
	_, err := q.db.Exec(ctx, upsertMembershipOnInvite, arg.WorkspaceID, arg.UserID, arg.Column3)
	return err
}
