/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Build info */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Version */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Version"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/onboarding/bootstrap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bootstrap a tenant and its first user
     * @description Creates the first tenant/user pair. Password auth is intentionally not implemented yet.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BootstrapInput"];
        };
      };
      responses: {
        /** @description Bootstrapped */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BootstrapResult"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new user account */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterInput"];
        };
      };
      responses: {
        /** @description Registered */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Password login → sets session cookie */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginInput"];
        };
      };
      responses: {
        /** @description Logged in */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Clear session */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current tenant user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user and tenant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["MeResult"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List accounts for current tenant */
    get: {
      parameters: {
        query?: {
          includeArchived?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accounts */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Account"][];
          };
        };
      };
    };
    put?: never;
    /** Create an account and opening balance snapshot */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AccountCreateInput"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Account"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/accounts/{accountId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an account */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          accountId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Account */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Account"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update mutable account fields */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          accountId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AccountUpdateInput"];
        };
      };
      responses: {
        /** @description Updated account */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Account"];
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List transactions for current tenant
     * @description Tenant is taken from the `X-Tenant-ID` context — never from the body.
     *     Results are ordered by `bookedAt DESC, id DESC`.
     */
    get: {
      parameters: {
        query?: {
          accountId?: string;
          from?: string;
          to?: string;
          status?: components["schemas"]["TransactionStatus"];
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Transactions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Transaction"][];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a manual transaction
     * @description Manual ledger entry. `tenantId` is resolved from `X-Tenant-ID`.
     *     `currency` must match the account currency (also enforced by a
     *     database trigger). Status defaults to `posted`.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TransactionCreateInput"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Transaction"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/transactions/{transactionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a transaction */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          transactionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Transaction */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Transaction"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Hard-delete a transaction (v1 — replace with soft-delete later) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          transactionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update mutable transaction fields
     * @description `accountId` is immutable in this slice. Nullable fields (categoryId,
     *     merchantId, counterpartyRaw, description, notes, valueAt, postedAt)
     *     accept an empty string to clear. `countAsExpense` accepts `true`,
     *     `false`, or `null` to clear.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          transactionId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TransactionUpdateInput"];
        };
      };
      responses: {
        /** @description Updated transaction */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Transaction"];
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/providers/gocardless/requisitions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a GoCardless bank connection (returns a consent URL) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            institutionId: string;
            label?: string;
          };
        };
      };
      responses: {
        /** @description Consent link */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              requisitionId?: string;
              /** Format: uri */
              consentUrl?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Version: {
      name: string;
      version: string;
    };
    User: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      tenantId: string;
      /** Format: email */
      email: string;
      displayName: string;
      /** Format: date-time */
      createdAt: string;
    };
    Tenant: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @example CHF */
      baseCurrency: string;
      cycleAnchorDay: number;
      /** @example en-CH */
      locale: string;
      /** @example Europe/Zurich */
      timezone: string;
      /** Format: date-time */
      createdAt: string;
    };
    BootstrapInput: {
      tenantName: string;
      /** @example CHF */
      baseCurrency: string;
      /** @default 1 */
      cycleAnchorDay: number;
      /** @example en-CH */
      locale: string;
      /**
       * @default UTC
       * @example Europe/Zurich
       */
      timezone: string;
      /** Format: email */
      email: string;
      displayName: string;
    };
    BootstrapResult: {
      tenant: components["schemas"]["Tenant"];
      user: components["schemas"]["User"];
    };
    MeResult: {
      tenant: components["schemas"]["Tenant"];
      user: components["schemas"]["User"];
    };
    RegisterInput: {
      /** Format: email */
      email: string;
      password: string;
      displayName: string;
      /** @default CHF */
      baseCurrency: string;
    };
    LoginInput: {
      /** Format: email */
      email: string;
      password: string;
    };
    /** @enum {string} */
    AccountKind:
      | "checking"
      | "savings"
      | "cash"
      | "credit_card"
      | "brokerage"
      | "crypto_wallet"
      | "loan"
      | "mortgage"
      | "asset"
      | "pillar_2"
      | "pillar_3a"
      | "other";
    Account: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      tenantId: string;
      name: string;
      nickname?: string | null;
      kind: components["schemas"]["AccountKind"];
      currency: string;
      institution?: string | null;
      /** Format: date-time */
      openDate: string;
      /** Format: date-time */
      closeDate?: string | null;
      /** @description Decimal as string */
      openingBalance: string;
      /** Format: date-time */
      openingBalanceDate: string;
      includeInNetworth: boolean;
      includeInSavingsRate: boolean;
      /** Format: date-time */
      archivedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @description Derived balance as decimal string: latest snapshot + posted/reconciled transactions booked on or after the snapshot's UTC date. */
      balance: string;
      /**
       * Format: date-time
       * @description as_of of the latest balance snapshot anchoring the derivation.
       */
      balanceAsOf?: string | null;
    };
    AccountCreateInput: {
      name: string;
      nickname?: string | null;
      kind: components["schemas"]["AccountKind"];
      currency: string;
      institution?: string | null;
      /** Format: date */
      openDate: string;
      /** @default 0 */
      openingBalance: string;
      /** Format: date */
      openingBalanceDate?: string;
      includeInNetworth?: boolean;
      includeInSavingsRate?: boolean;
    };
    AccountUpdateInput: {
      name?: string;
      /** @description Send empty string to clear. */
      nickname?: string | null;
      /** @description Send empty string to clear. */
      institution?: string | null;
      includeInNetworth?: boolean;
      includeInSavingsRate?: boolean;
      /**
       * Format: date
       * @description Send empty string to clear.
       */
      closeDate?: string | null;
      archived?: boolean;
    };
    /** @enum {string} */
    TransactionStatus: "draft" | "posted" | "reconciled" | "voided";
    Transaction: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      tenantId: string;
      /** Format: uuid */
      accountId: string;
      status: components["schemas"]["TransactionStatus"];
      /** Format: date */
      bookedAt: string;
      /** Format: date */
      valueAt?: string | null;
      /** Format: date-time */
      postedAt?: string | null;
      /** @description Signed decimal as string, always in the account currency. */
      amount: string;
      /** @description Must match the account currency. */
      currency: string;
      /** @description Pre-FX amount when booked in a foreign currency. */
      originalAmount?: string | null;
      originalCurrency?: string | null;
      /** Format: uuid */
      merchantId?: string | null;
      /** Format: uuid */
      categoryId?: string | null;
      counterpartyRaw?: string | null;
      description?: string | null;
      notes?: string | null;
      /** @description User override. null defers to the derived rule. */
      countAsExpense?: boolean | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    TransactionCreateInput: {
      /** Format: uuid */
      accountId: string;
      /** @default posted */
      status: components["schemas"]["TransactionStatus"];
      /** Format: date */
      bookedAt: string;
      /** Format: date */
      valueAt?: string | null;
      /** Format: date-time */
      postedAt?: string | null;
      /** @description Signed decimal as string. */
      amount: string;
      currency: string;
      /** Format: uuid */
      categoryId?: string | null;
      /** Format: uuid */
      merchantId?: string | null;
      counterpartyRaw?: string | null;
      description?: string | null;
      notes?: string | null;
      countAsExpense?: boolean | null;
    };
    /**
     * @description All fields optional. Send empty string on nullable string/date/uuid
     *     fields to clear them (valueAt, postedAt, categoryId, merchantId,
     *     counterpartyRaw, description, notes). countAsExpense accepts true,
     *     false, or null to clear. accountId is not patchable.
     */
    TransactionUpdateInput: {
      status?: components["schemas"]["TransactionStatus"];
      /** Format: date */
      bookedAt?: string;
      /** Format: date */
      valueAt?: string | null;
      /** Format: date-time */
      postedAt?: string | null;
      amount?: string;
      currency?: string;
      /** Format: uuid */
      categoryId?: string | null;
      /** Format: uuid */
      merchantId?: string | null;
      counterpartyRaw?: string | null;
      description?: string | null;
      notes?: string | null;
      countAsExpense?: boolean | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
